"""Generate taxonomy/hierarchy/uk_ew.csv and uk_ni.csv.

The UK is four censuses (sources/uk.md); two of them need allocating and each needs its own
parent file, because neither encodes its hierarchy anywhere except in the label text.

ENGLAND AND WALES. TS030 gives 8 religion categories at Output Area; TS031 gives 60 at MSOA,
and the extra 50 are write-ins labelled `Other religion: Pagan`, `No religion: Agnostic` and
so on. So the parent IS the text before the colon, and this derives it rather than asserting
it. Note what is NOT in that list: **no Christian denominations at all.** 27.5M Christians in
England and Wales and ONS publishes not one denomination for them, at any geography. That is
spec §3.11's irreducible floor, and it is the single largest unresolved block on this map.

NORTHERN IRELAND. MS-B19 gives 7 categories at Data Zone; MS-B20 gives 32 at LGD. Here the
colon rule is NOT enough: `Christian: Baptist` cannot go to `Christian`, because there is no
`Christian` column at Data Zone — NISRA publishes the four big denominations by name and
everything else as `Other Christian (including Christian related)`. So the four are matched
by name and the rest fall to the residual, which is a rule, not a list.

Both are validated by allocate.py afterwards: every column's children are summed against the
column's own total, so a mis-assignment here shows up as a column that will not reconcile.

Run: python taxonomy/hierarchy/make_uk.py
"""

import os
import sys

import pandas as pd

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
SRC = os.path.join(ROOT, "data", "normalized", "uk.csv")

# NI: the four denominations NISRA publishes by name at Data Zone. Everything else Christian
# goes to its residual column.
NI_NAMED = {
    "Christian: Catholic": "Catholic",
    "Christian: Presbyterian Church in Ireland": "Presbyterian Church in Ireland",
    "Christian: Church of Ireland": "Church of Ireland",
    "Christian: Methodist Church in Ireland": "Methodist Church in Ireland",
}
NI_OTHER_CHRISTIAN = "Other Christian (including Christian related)"

EW_HEADER = """\
# England and Wales (ONS): TS031 MSOA category -> the TS030 Output Area column it belongs to.
# GENERATED by taxonomy/hierarchy/make_uk.py — the parent is the text before the colon.
# Do not hand-edit.
#
# ONS publishes NO Christian denominations at any geography, so `Christian` is a leaf here
# and 27.5M people stay one undifferentiated node (spec §3.11).
"""

NI_HEADER = """\
# Northern Ireland (NISRA): MS-B20 LGD category -> the MS-B19 Data Zone column.
# GENERATED by taxonomy/hierarchy/make_uk.py — four denominations matched by name, the rest
# of the Christian branch to NISRA's own residual column. Do not hand-edit.
#
# This is the CURRENT-religion question. NISRA asks a second one, religion brought up in
# (MS-B23/B24), which is a different variable and is not allocated or drawn (uk.md §1).
"""


def write(path, header, rows):
    with open(path, "w", encoding="utf-8", newline="") as fh:
        fh.write(header)
        rows.to_csv(fh, index=False)
    print(f"wrote {path}  ({len(rows)} categories)")


def main():
    d = pd.read_csv(SRC, dtype={"geo_id": str}, low_memory=False)

    # ---------------------------------------------------------------- England and Wales
    ew = d[d["source_id"] == "uk_ew_census_2021"]
    fine = set(ew.loc[ew["geo_level"] == "output_area", "source_category"])
    coarse = sorted(set(ew.loc[ew["geo_level"] == "msoa", "source_category"]))

    rows = []
    for c in coarse:
        parent = c.split(":", 1)[0].strip() if ":" in c else c
        rows.append((c, parent))
    ew_rows = pd.DataFrame(rows, columns=["source_category", "parent"])

    unknown = sorted(set(ew_rows["parent"]) - fine)
    print(f"England and Wales: {len(coarse)} MSOA categories, "
          f"{len(fine)} Output Area columns")
    print(f"  parents not published at Output Area (become leaves or are dropped): {unknown}")
    write(os.path.join(HERE, "uk_ew.csv"), EW_HEADER, ew_rows)

    # ---------------------------------------------------------------- Northern Ireland
    ni = d[d["source_id"] == "uk_ni_census_2021"]
    ni_fine = set(ni.loc[ni["geo_level"] == "data_zone", "source_category"])
    ni_coarse = sorted(set(ni.loc[ni["geo_level"] == "lgd", "source_category"]))

    rows, unmatched = [], []
    for c in ni_coarse:
        if c in NI_NAMED:
            parent = NI_NAMED[c]
        elif c.startswith("Christian:"):
            parent = NI_OTHER_CHRISTIAN
        elif c.startswith("Other Religions:"):
            parent = "Other religions"
        elif c in ni_fine:
            parent = c
        else:
            parent = None
            unmatched.append(c)
        rows.append((c, parent))
    ni_rows = pd.DataFrame(rows, columns=["source_category", "parent"])
    ni_rows = ni_rows[ni_rows["parent"].notna()]

    print(f"\nNorthern Ireland: {len(ni_coarse)} LGD categories, "
          f"{len(ni_fine)} Data Zone columns")
    print(f"  no Data Zone home, dropped: {unmatched}")
    for p, sub in ni_rows.groupby("parent"):
        print(f"    {len(sub):>2} -> {p}")
    write(os.path.join(HERE, "uk_ni.csv"), NI_HEADER, ni_rows)


if __name__ == "__main__":
    main()
