"""Generate taxonomy/hierarchy/nz.csv — the Stats NZ level-3 -> level-1 join.

nz.csv holds 166 categories at NATIONAL level from the 2018 census and 13 at SA2 from 2023
(spec §3.4: structure from the detailed source, totals from the recent one). allocate.py
needs to know which SA2 column each national category belongs to, and the two tables share
no key: the SA2 rows carry no classification code at all.

They do not need one. The national code IS the hierarchy — Stats NZ's religious affiliation
classification is nested, and the first two digits are the level-1 group. So this derives
the join from the codes rather than asserting 166 rows by hand, and prints the group totals
so the assignment can be read against the SA2 column names it claims to match.

Two groups take more than one prefix, which is why the mapping is a table and not `code[:1]`:
Christian is 20 + 21 + 29, and Other Religions is 80 + 81.

Run: python taxonomy/hierarchy/make_nz.py
"""

import os
import sys

import pandas as pd

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
SRC = os.path.join(ROOT, "data", "normalized", "nz.csv")
OUT = os.path.join(HERE, "nz.csv")

# Stats NZ level-1 group <- the level-3 code prefixes that belong to it.
GROUP = {
    "00": "No Religion",
    "10": "Buddhism",
    "20": "Christian",
    "21": "Christian",
    "29": "Christian",
    "30": "Hinduism",
    "40": "Islam",
    "50": "Judaism",
    "60": "Māori Religions, Beliefs and Philosophies",
    "70": "Spiritualism and New Age Religions",
    "80": "Other Religions, Beliefs and Philosophies",
    "81": "Other Religions, Beliefs and Philosophies",
    "94": "Residual Categories",
    "95": "Object to answering",
    "97": "Residual Categories",
    "98": "Residual Categories",
    "99": "Residual Categories",
}

HEADER = """\
# Stats NZ religious affiliation: level-3 category -> the level-1 column published at SA2.
# GENERATED by taxonomy/hierarchy/make_nz.py from the level-3 codes in nz.csv's `note`.
# Do not hand-edit; change the GROUP table in that script instead.
#
# The 2018 national table has 166 level-3 categories; the 2023 SA2 table has 13 level-1
# columns and no code of any kind, so this is the only bridge between them. Derived from
# the first two digits of the level-3 code, which is what Stats NZ nests on.
"""


def main():
    d = pd.read_csv(SRC, low_memory=False)
    n = d[d["geo_level"] == "national"].copy()
    n["code"] = n["note"].str.extract(r"code (\d+)")
    n = n[n["code"].notna()].copy()
    n["g"] = n["code"].str[:2]

    unknown = sorted(set(n["g"]) - set(GROUP))
    if unknown:
        raise SystemExit(f"code prefixes with no level-1 group: {unknown}")

    fine = set(d.loc[d["geo_level"] == "sa2", "source_category"])
    bad = sorted(set(GROUP.values()) - fine)
    if bad:
        raise SystemExit(f"group names that are not SA2 columns: {bad}")

    n["parent"] = n["g"].map(GROUP)
    dup = n["source_category"].duplicated().sum()
    if dup:
        raise SystemExit(f"{dup} duplicate national category names")

    for parent, sub in n.groupby("parent"):
        print(f"  {sub['count'].sum():>10,.0f}  {len(sub):>3} cats -> {parent}")

    out = n[["source_category", "parent"]].sort_values(["parent", "source_category"])
    with open(OUT, "w", encoding="utf-8", newline="") as fh:
        fh.write(HEADER)
        out.to_csv(fh, index=False)
    print(f"\nwrote {OUT}  ({len(out)} categories)")


if __name__ == "__main__":
    main()
