# build_names.py — produce data/names_en.json: English names for every
# operator, line and station in segments.geojson.
#
#   operators  curated JP->EN table (178)
#   lines      curated JP->EN table (454 op|line pairs)
#   stations   matched against OpenStreetMap `name:en` (osm_jp_stations.json),
#              disambiguated by coordinate; gaps filled by STATIONS_MANUAL.
#
# OSM source:  data/osm_jp_stations.json — every railway station/halt/tram_stop
#   node in Japan, pulled once from Overpass (User-Agent header required):
#     [out:json][timeout:270];
#     (node["railway"~"^(station|halt|tram_stop)$"](24,122,46,154););out;
#
# Run after build_census.py.  Output is keyed "op||name" so index.html can
# rebuild the keys from feature properties with no runtime geo-matching.

import json, math, os, re, statistics, sys, io, unicodedata
from collections import defaultdict

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')
HERE = __file__.rsplit('\\', 1)[0].rsplit('/', 1)[0]

# ───────────────────────────── operators (178) ─────────────────────────────
OPERATORS_EN = {
    'IRいしかわ鉄道': 'IR Ishikawa Railway',
    'WILLER　TRAINS': 'Willer Trains',
    'あいの風とやま鉄道': 'Ainokaze Toyama Railway',
    'いすみ鉄道': 'Isumi Railway',
    'えちごトキめき鉄道': 'Echigo Tokimeki Railway',
    'えちぜん鉄道': 'Echizen Railway',
    'くま川鉄道': 'Kumagawa Railroad',
    'しなの鉄道': 'Shinano Railway',
    'とさでん交通': 'Tosaden Kotsu',
    'のと鉄道': 'Noto Railway',
    'ひたちなか海浜鉄道': 'Hitachinaka Seaside Railway',
    'ゆりかもめ': 'Yurikamome',
    'わたらせ渓谷鐵道': 'Watarase Keikoku Railway',
    'アイジーアールいわて銀河鉄道': 'IGR Iwate Galaxy Railway',
    'アルピコ交通': 'Alpico Kotsu',
    'スカイレールサービス': 'Skyrail Service',
    'ラクテンチ': 'Beppu Rakutenchi',
    '一畑電車': 'Ichibata Electric Railway',
    '万葉線': 'Manyosen',
    '三岐鉄道': 'Sangi Railway',
    '三陸鉄道': 'Sanriku Railway',
    '上信電鉄': 'Joshin Electric Railway',
    '上毛電気鉄道': 'Jomo Electric Railway',
    '上田電鉄': 'Ueda Electric Railway',
    '丹後海陸交通': 'Tankai Kotsu',
    '九州旅客鉄道': 'JR Kyushu',
    '井原鉄道': 'Ibara Railway',
    '京成電鉄': 'Keisei Electric Railway',
    '京浜急行電鉄': 'Keikyu',
    '京王電鉄': 'Keio',
    '京福電気鉄道': 'Keifuku Electric Railroad',
    '京都市': 'Kyoto Municipal Subway',
    '京阪電気鉄道': 'Keihan Electric Railway',
    '仙台市': 'Sendai Municipal Subway',
    '仙台空港鉄道': 'Sendai Airport Transit',
    '伊予鉄道': 'Iyo Railway',
    '伊勢鉄道': 'Ise Railway',
    '伊豆急行': 'Izukyu',
    '伊豆箱根鉄道': 'Izuhakone Railway',
    '伊賀鉄道': 'Iga Railway',
    '会津鉄道': 'Aizu Railway',
    '信楽高原鐵道': 'Shigaraki Kohgen Railway',
    '六甲山観光': 'Rokkosan Tourism',
    '函館市': 'Hakodate City Tram',
    '北九州高速鉄道': 'Kitakyushu Monorail',
    '北大阪急行電鉄': 'Kita-Osaka Kyuko Railway',
    '北条鉄道': 'Hojo Railway',
    '北海道旅客鉄道': 'JR Hokkaido',
    '北総鉄道': 'Hokuso Railway',
    '北越急行': 'Hokuetsu Express',
    '北陸鉄道': 'Hokuriku Railroad',
    '十国峠': 'Jukkoku Pass',
    '千葉都市モノレール': 'Chiba Urban Monorail',
    '南海電気鉄道': 'Nankai',
    '南阿蘇鉄道': 'Minamiaso Railway',
    '叡山電鉄': 'Eizan Electric Railway',
    '名古屋ガイドウェイバス': 'Nagoya Guideway Bus',
    '名古屋市': 'Nagoya Municipal Subway',
    '名古屋臨海高速鉄道': 'Nagoya Rinkai Rapid Transit',
    '名古屋鉄道': 'Meitetsu',
    '和歌山電鐵': 'Wakayama Electric Railway',
    '四国ケーブル': 'Shikoku Cable',
    '四国旅客鉄道': 'JR Shikoku',
    '四日市あすなろう鉄道': 'Yokkaichi Asunarou Railway',
    '土佐くろしお鉄道': 'Tosa Kuroshio Railway',
    '埼玉新都市交通': 'Saitama New Urban Transit',
    '埼玉高速鉄道': 'Saitama Rapid Railway',
    '多摩都市モノレール': 'Tama Monorail',
    '大井川鐵道': 'Oigawa Railway',
    '大山観光電鉄': 'Oyama Tourist Electric Railway',
    '大阪モノレール': 'Osaka Monorail',
    '大阪市高速電気軌道': 'Osaka Metro',
    '天竜浜名湖鉄道': 'Tenryu Hamanako Railroad',
    '宇都宮ライトレール': 'Utsunomiya Light Rail',
    '富士山麓鉄道': 'Fujikyu Railway',
    '富山地方鉄道': 'Toyama Chiho Railway',
    '小湊鐵道': 'Kominato Railway',
    '小田急電鉄': 'Odakyu',
    '山万': 'Yamaman',
    '山形鉄道': 'Yamagata Railway',
    '山陽電気鉄道': 'Sanyo Electric Railway',
    '岡山電気軌道': 'Okayama Electric Tramway',
    '岳南電車': 'Gakunan Railway',
    '島原鉄道': 'Shimabara Railway',
    '嵯峨野観光鉄道': 'Sagano Scenic Railway',
    '平成筑豊鉄道': 'Heisei Chikuho Railway',
    '広島電鉄': 'Hiroshima Electric Railway',
    '広島高速交通': 'Hiroshima Rapid Transit',
    '弘南鉄道': 'Konan Railway',
    '御岳登山鉄道': 'Mitake Tozan Railway',
    '愛知環状鉄道': 'Aichi Loop Railway',
    '愛知高速交通': 'Aichi Rapid Transit',
    '新京成電鉄': 'Shin-Keisei Electric Railway',
    '明知鉄道': 'Akechi Railway',
    '智頭急行': 'Chizu Express',
    '札幌市': 'Sapporo Municipal Subway',
    '札幌市交通事業振興公社': 'Sapporo Streetcar',
    '東京モノレール': 'Tokyo Monorail',
    '東京地下鉄': 'Tokyo Metro',
    '東京臨海高速鉄道': 'Tokyo Rinkai Rapid Transit',
    '東京都': 'Toei',
    '東急電鉄': 'Tokyu',
    '東日本旅客鉄道': 'JR East',
    '東武鉄道': 'Tobu Railway',
    '東海交通事業': 'Tokai Transport Service',
    '東海旅客鉄道': 'JR Central',
    '東葉高速鉄道': 'Toyo Rapid Railway',
    '松浦鉄道': 'Matsuura Railway',
    '横浜シーサイドライン': 'Yokohama Seaside Line',
    '横浜市': 'Yokohama Municipal Subway',
    '横浜高速鉄道': 'Yokohama Minatomirai Railway',
    '樽見鉄道': 'Tarumi Railway',
    '比叡山鉄道': 'Hieizan Railway',
    '水島臨海鉄道': 'Mizushima Rinkai Railway',
    '水間鉄道': 'Mizuma Railway',
    '江ノ島電鉄': 'Enoshima Electric Railway',
    '沖縄都市モノレール': 'Okinawa Urban Monorail',
    '泉北高速鉄道': 'Semboku Rapid Railway',
    '津軽鉄道': 'Tsugaru Railway',
    '流鉄': 'Ryutetsu',
    '湘南モノレール': 'Shonan Monorail',
    '熊本市': 'Kumamoto City Tram',
    '熊本電気鉄道': 'Kumamoto Electric Railway',
    '甘木鉄道': 'Amagi Railway',
    '由利高原鉄道': 'Yuri Kogen Railway',
    '皿倉登山鉄道': 'Sarakura Tozan Railway',
    '相模鉄道': 'Sotetsu',
    '真岡鐵道': 'Moka Railway',
    '神戸すまいまちづくり公社': 'Kobe City Urban Development',
    '神戸市': 'Kobe Municipal Subway',
    '神戸新交通': 'Kobe New Transit',
    '神戸電鉄': 'Kobe Electric Railway',
    '福井鉄道': 'Fukui Railway',
    '福岡市': 'Fukuoka City Subway',
    '福島交通': 'Fukushima Transportation',
    '秋田内陸縦貫鉄道': 'Akita Nairiku Jukan Railway',
    '秩父鉄道': 'Chichibu Railway',
    '立山黒部貫光': 'Tateyama Kurobe Kanko',
    '筑波観光鉄道': 'Tsukuba Kanko Railway',
    '筑豊電気鉄道': 'Chikuho Electric Railroad',
    '箱根登山鉄道': 'Hakone Tozan Railway',
    '紀州鉄道': 'Kishu Railway',
    '肥薩おれんじ鉄道': 'Hisatsu Orange Railway',
    '能勢電鉄': 'Nose Electric Railway',
    '舞浜リゾートライン': 'Maihama Resort Line',
    '芝山鉄道': 'Shibayama Railway',
    '若桜鉄道': 'Wakasa Railway',
    '西日本旅客鉄道': 'JR West',
    '西日本鉄道': 'Nishitetsu',
    '西武鉄道': 'Seibu Railway',
    '豊橋鉄道': 'Toyohashi Railroad',
    '近江鉄道': 'Ohmi Railway',
    '近畿日本鉄道': 'Kintetsu',
    '道南いさりび鉄道': 'South Hokkaido Railway',
    '遠州鉄道': 'Enshu Railway',
    '野岩鉄道': 'Yagan Railway',
    '銚子電気鉄道': 'Choshi Electric Railway',
    '錦川鉄道': 'Nishikigawa Railway',
    '長崎電気軌道': 'Nagasaki Electric Tramway',
    '長良川鉄道': 'Nagaragawa Railway',
    '長野電鉄': 'Nagano Electric Railway',
    '関東鉄道': 'Kanto Railway',
    '阪堺電気軌道': 'Hankai Tramway',
    '阪急電鉄': 'Hankyu',
    '阪神電気鉄道': 'Hanshin Electric Railway',
    '阿佐海岸鉄道': 'Asa Coast Railway',
    '阿武隈急行': 'Abukuma Express',
    '青い森鉄道': 'Aoimori Railway',
    '青函トンネル記念館': 'Seikan Tunnel Museum',
    '静岡鉄道': 'Shizuoka Railway',
    '鞍馬寺': 'Kurama-dera',
    '養老鉄道': 'Yoro Railway',
    '首都圏新都市鉄道': 'Metropolitan Intercity Railway',
    '高尾登山電鉄': 'Takao Tozan Railway',
    '高松琴平電気鉄道': 'Kotoden',
    '鹿児島市': 'Kagoshima City Tram',
    '鹿島臨海鉄道': 'Kashima Rinkai Railway',
    '黒部峡谷鉄道': 'Kurobe Gorge Railway',
    '一般社団法人札幌市交通事業振興公社': 'Sapporo Streetcar',
    '一般財団法人青函トンネル記念館': 'Seikan Tunnel Museum',
    '関西電力': 'Kansai Electric Power',
}

# ──────────────────────── lines, keyed "op||line" (454) ─────────────────────
LINES_EN = {
    'IRいしかわ鉄道||IRいしかわ鉄道線': 'IR Ishikawa Railway Line',
    'WILLER　TRAINS||宮福線・宮津線': 'Miyafuku Line / Miyazu Line',
    'あいの風とやま鉄道||あいの風とやま鉄道線': 'Ainokaze Toyama Railway Line',
    'いすみ鉄道||いすみ線': 'Isumi Line',
    'えちごトキめき鉄道||妙高はねうまライン': 'Myoko Haneuma Line',
    'えちごトキめき鉄道||日本海ひすいライン': 'Nihonkai Hisui Line',
    'えちぜん鉄道||勝山永平寺線・三国芦原線': 'Katsuyama Eiheiji Line / Mikuni Awara Line',
    'くま川鉄道||湯前線': 'Yunomae Line',
    'しなの鉄道||しなの鉄道線': 'Shinano Railway Line',
    'しなの鉄道||北しなの線': 'Kita-Shinano Line',
    'とさでん交通||軌道線': 'Tosaden Tram Line',
    'のと鉄道||七尾線': 'Nanao Line',
    'ひたちなか海浜鉄道||湊線': 'Minato Line',
    'ゆりかもめ||東京臨海新交通臨海線': 'Yurikamome Line',
    'わたらせ渓谷鐵道||わたらせ渓谷線': 'Watarase Keikoku Line',
    'アイジーアールいわて銀河鉄道||いわて銀河鉄道線': 'Iwate Galaxy Railway Line',
    'アルピコ交通||上高地線': 'Kamikochi Line',
    'スカイレールサービス||広島短距離交通瀬野線': 'Skyrail Midorizaka Line',
    'ラクテンチ||別府ラクテンチケーブル線': 'Beppu Rakutenchi Cable Line',
    '一畑電車||北松江線・大社線': 'Kita-Matsue Line / Taisha Line',
    '万葉線||万葉線': 'Manyosen Line',
    '三岐鉄道||三岐線・北勢線': 'Sangi Line / Hokusei Line',
    '三陸鉄道||リアス線': 'Rias Line',
    '上信電鉄||上信線': 'Joshin Line',
    '上毛電気鉄道||上毛線': 'Jomo Line',
    '上田電鉄||別所線': 'Bessho Line',
    '丹後海陸交通||天橋立鋼索鉄道': 'Amanohashidate Cable Railway',
    '九州旅客鉄道||三角線': 'Misumi Line',
    '九州旅客鉄道||久大本線': 'Kyudai Main Line',
    '九州旅客鉄道||九州新幹線': 'Kyushu Shinkansen',
    '九州旅客鉄道||佐世保線': 'Sasebo Line',
    '九州旅客鉄道||吉都線': 'Kitto Line',
    '九州旅客鉄道||唐津線': 'Karatsu Line',
    '九州旅客鉄道||大村線': 'Omura Line',
    '九州旅客鉄道||宮崎空港線': 'Miyazaki Airport Line',
    '九州旅客鉄道||山陽本線': 'Sanyo Main Line',
    '九州旅客鉄道||後藤寺線': 'Gotoji Line',
    '九州旅客鉄道||指宿枕崎線': 'Ibusuki-Makurazaki Line',
    '九州旅客鉄道||日南線': 'Nichinan Line',
    '九州旅客鉄道||日田彦山線': 'Hitahikosan Line',
    '九州旅客鉄道||日豊本線': 'Nippo Main Line',
    '九州旅客鉄道||筑肥線': 'Chikuhi Line',
    '九州旅客鉄道||筑豊本線': 'Chikuho Main Line',
    '九州旅客鉄道||篠栗線': 'Sasaguri Line',
    '九州旅客鉄道||肥薩線': 'Hisatsu Line',
    '九州旅客鉄道||西九州新幹線': 'Nishi Kyushu Shinkansen',
    '九州旅客鉄道||豊肥本線': 'Hohi Main Line',
    '九州旅客鉄道||長崎本線': 'Nagasaki Main Line',
    '九州旅客鉄道||香椎線': 'Kashii Line',
    '九州旅客鉄道||鹿児島本線': 'Kagoshima Main Line',
    '井原鉄道||井原線': 'Ibara Line',
    '京成電鉄||千原線': 'Chihara Line',
    '京成電鉄||千葉線': 'Chiba Line',
    '京成電鉄||成田空港線': 'Narita Airport Line',
    '京成電鉄||押上線': 'Oshiage Line',
    '京成電鉄||本線': 'Keisei Main Line',
    '京成電鉄||東成田線': 'Higashi-Narita Line',
    '京成電鉄||金町線': 'Kanamachi Line',
    '京浜急行電鉄||久里浜線': 'Kurihama Line',
    '京浜急行電鉄||大師線': 'Daishi Line',
    '京浜急行電鉄||本線': 'Keikyu Main Line',
    '京浜急行電鉄||空港線': 'Airport Line',
    '京浜急行電鉄||逗子線': 'Zushi Line',
    '京王電鉄||井の頭線': 'Inokashira Line',
    '京王電鉄||京王線・高尾線・相模原線': 'Keio Line / Takao Line / Sagamihara Line',
    '京福電気鉄道||嵐山本線・北野線': 'Arashiyama Main Line / Kitano Line',
    '京福電気鉄道||鋼索線': 'Eizan Cable Line',
    '京都市||東西線': 'Tozai Line',
    '京都市||烏丸線': 'Karasuma Line',
    '京阪電気鉄道||京津線・石山坂本線': 'Keishin Line / Ishiyama-Sakamoto Line',
    '京阪電気鉄道||京阪本線・鴨東線・中之島線': 'Keihan Main Line / Oto Line / Nakanoshima Line',
    '京阪電気鉄道||鋼索線': 'Keihan Cable Line',
    '仙台市||南北線・東西線': 'Namboku Line / Tozai Line',
    '仙台空港鉄道||仙台空港線': 'Sendai Airport Line',
    '伊予鉄道||松山市内軌道線': 'Matsuyama City Tram',
    '伊予鉄道||高浜線・横河原線・郡中線': 'Takahama Line / Yokogawara Line / Gunchu Line',
    '伊勢鉄道||伊勢線': 'Ise Line',
    '伊豆急行||伊豆急行線': 'Izukyu Line',
    '伊豆箱根鉄道||大雄山線': 'Daiyuzan Line',
    '伊豆箱根鉄道||駿豆線': 'Sunzu Line',
    '伊賀鉄道||伊賀線': 'Iga Line',
    '会津鉄道||会津線': 'Aizu Line',
    '信楽高原鐵道||信楽線': 'Shigaraki Line',
    '六甲山観光||六甲ケーブル線': 'Rokko Cable Line',
    '函館市||函館市内軌道線': 'Hakodate City Tram',
    '北九州高速鉄道||小倉線': 'Kokura Line',
    '北大阪急行電鉄||南北線': 'Namboku Line',
    '北条鉄道||北条線': 'Hojo Line',
    '北海道旅客鉄道||函館線': 'Hakodate Main Line',
    '北海道旅客鉄道||北海道新幹線': 'Hokkaido Shinkansen',
    '北海道旅客鉄道||千歳・室蘭線': 'Chitose Line / Muroran Main Line',
    '北海道旅客鉄道||宗谷線': 'Soya Main Line',
    '北海道旅客鉄道||室蘭線': 'Muroran Main Line',
    '北海道旅客鉄道||富良野線': 'Furano Line',
    '北海道旅客鉄道||日高線': 'Hidaka Main Line',
    '北海道旅客鉄道||札沼線': 'Sassho Line',
    '北海道旅客鉄道||根室線': 'Nemuro Main Line',
    '北海道旅客鉄道||海峡線': 'Kaikyo Line',
    '北海道旅客鉄道||留萌線': 'Rumoi Main Line',
    '北海道旅客鉄道||石勝・根室線': 'Sekisho Line / Nemuro Main Line',
    '北海道旅客鉄道||石北線': 'Sekihoku Main Line',
    '北海道旅客鉄道||釧網線': 'Senmo Main Line',
    '北総鉄道||北総線': 'Hokuso Line',
    '北越急行||ほくほく線': 'Hokuhoku Line',
    '北陸鉄道||浅野川線': 'Asanogawa Line',
    '北陸鉄道||石川線': 'Ishikawa Line',
    '十国峠||十国鋼索線': 'Jukkoku Cable Line',
    '千葉都市モノレール||1号線・2号線': 'Line 1 / Line 2',
    '南海電気鉄道||南海本線': 'Nankai Main Line',
    '南海電気鉄道||鋼索線': 'Koyasan Cable Line',
    '南海電気鉄道||高野線': 'Koya Line',
    '南阿蘇鉄道||高森線': 'Takamori Line',
    '叡山電鉄||叡山本線・鞍馬線': 'Eizan Main Line / Kurama Line',
    '名古屋ガイドウェイバス||ガイドウェイバス志段味線': 'Yutorito Line',
    '名古屋市||上飯田線': 'Kamiiida Line',
    '名古屋市||名城線・名港線': 'Meijo Line / Meiko Line',
    '名古屋市||東山線': 'Higashiyama Line',
    '名古屋市||桜通線': 'Sakura-dori Line',
    '名古屋市||鶴舞線': 'Tsurumai Line',
    '名古屋臨海高速鉄道||西名古屋港線': 'Aonami Line',
    '名古屋鉄道||名古屋本線': 'Meitetsu Nagoya Main Line',
    '名古屋鉄道||瀬戸線': 'Seto Line',
    '名古屋鉄道||豊川線': 'Toyokawa Line',
    '和歌山電鐵||貴志川線': 'Kishigawa Line',
    '四国ケーブル||八栗ケーブル': 'Yakuri Cable',
    '四国旅客鉄道||予土線': 'Yodo Line',
    '四国旅客鉄道||予讃線': 'Yosan Line',
    '四国旅客鉄道||内子線': 'Uchiko Line',
    '四国旅客鉄道||土讃線': 'Dosan Line',
    '四国旅客鉄道||徳島線': 'Tokushima Line',
    '四国旅客鉄道||本四備讃線': 'Honshi-Bisan Line',
    '四国旅客鉄道||牟岐線': 'Mugi Line',
    '四国旅客鉄道||高徳線': 'Kotoku Line',
    '四国旅客鉄道||鳴門線': 'Naruto Line',
    '四日市あすなろう鉄道||内部線・八王子線': 'Utsube Line / Hachioji Line',
    '土佐くろしお鉄道||中村線・宿毛線・阿佐線': 'Nakamura Line / Sukumo Line / Asa Line',
    '埼玉新都市交通||伊奈線': 'Ina Line',
    '埼玉高速鉄道||埼玉高速鉄道線': 'Saitama Rapid Railway Line',
    '多摩都市モノレール||多摩都市モノレール線': 'Tama Monorail Line',
    '大井川鐵道||大井川本線・井川線': 'Oigawa Main Line / Ikawa Line',
    '大山観光電鉄||大山鋼索線': 'Oyama Cable Line',
    '大阪モノレール||大阪モノレール線・国際文化公園都市モノレール線（彩都線）': 'Osaka Monorail Line / Saito Line',
    '大阪市高速電気軌道||1号線(御堂筋線)': 'Midosuji Line',
    '大阪市高速電気軌道||2号線(谷町線)': 'Tanimachi Line',
    '大阪市高速電気軌道||3号線(四つ橋線)': 'Yotsubashi Line',
    '大阪市高速電気軌道||4号線(中央線)': 'Chuo Line',
    '大阪市高速電気軌道||5号線(千日前線)': 'Sennichimae Line',
    '大阪市高速電気軌道||6号線(堺筋線)': 'Sakaisuji Line',
    '大阪市高速電気軌道||7号線(長堀鶴見緑地線)': 'Nagahori Tsurumi-ryokuchi Line',
    '大阪市高速電気軌道||8号線（今里筋線）': 'Imazatosuji Line',
    '大阪市高速電気軌道||南港ポートタウン線': 'Nanko Port Town Line',
    '天竜浜名湖鉄道||天竜浜名湖線': 'Tenryu Hamanako Line',
    '宇都宮ライトレール||宇都宮芳賀ライトレール線': 'Utsunomiya-Haga Light Rail Line',
    '富士山麓鉄道||大月線・河口湖線': 'Otsuki Line / Kawaguchiko Line',
    '富山地方鉄道||上滝線': 'Kamidaki Line',
    '富山地方鉄道||不二越線': 'Fujikoshi Line',
    '富山地方鉄道||富山市内軌道線': 'Toyama City Tram',
    '富山地方鉄道||本線': 'Toyama Chiho Main Line',
    '富山地方鉄道||立山線': 'Tateyama Line',
    '小湊鐵道||小湊鐵道線': 'Kominato Line',
    '小田急電鉄||多摩線': 'Tama Line',
    '小田急電鉄||小田原線・江ノ島線': 'Odawara Line / Enoshima Line',
    '山万||ユーカリが丘線': 'Yukarigaoka Line',
    '山形鉄道||フラワー長井線': 'Flower Nagai Line',
    '山陽電気鉄道||本線・網干線': 'Sanyo Main Line / Aboshi Line',
    '岡山電気軌道||東山本線・清輝橋線': 'Higashiyama Main Line / Seikibashi Line',
    '岳南電車||岳南線': 'Gakunan Line',
    '島原鉄道||島原鉄道線': 'Shimabara Railway Line',
    '嵯峨野観光鉄道||嵯峨野観光線': 'Sagano Scenic Line',
    '平成筑豊鉄道||伊田線・糸田線・田川線': 'Ita Line / Itoda Line / Tagawa Line',
    '平成筑豊鉄道||門司港レトロ観光線': 'Mojiko Retro Sightseeing Line',
    '広島電鉄||宮島線': 'Miyajima Line',
    '広島電鉄||広島市内軌道線': 'Hiroshima City Tram',
    '広島高速交通||広島新交通1号線': 'Astram Line',
    '弘南鉄道||大鰐線': 'Owani Line',
    '弘南鉄道||弘南線': 'Konan Line',
    '御岳登山鉄道||ケーブルカー': 'Mitake Tozan Cable Line',
    '愛知環状鉄道||愛知環状鉄道線': 'Aichi Loop Line',
    '愛知高速交通||東部丘陵線': 'Tobu Kyuryo Line',
    '新京成電鉄||新京成線': 'Shin-Keisei Line',
    '明知鉄道||明知線': 'Akechi Line',
    '智頭急行||智頭線': 'Chizu Line',
    '札幌市||南北線': 'Namboku Line',
    '札幌市||東西線': 'Tozai Line',
    '札幌市||東豊線': 'Toho Line',
    '札幌市交通事業振興公社||一条・山鼻軌道線': 'Sapporo City Tram',
    '東京モノレール||東京モノレール羽田線': 'Tokyo Monorail Haneda Line',
    '東京地下鉄||11号線半蔵門線': 'Hanzomon Line',
    '東京地下鉄||13号線副都心線': 'Fukutoshin Line',
    '東京地下鉄||2号線日比谷線': 'Hibiya Line',
    '東京地下鉄||3号線銀座線': 'Ginza Line',
    '東京地下鉄||4号線丸ノ内線': 'Marunouchi Line',
    '東京地下鉄||5号線東西線': 'Tozai Line',
    '東京地下鉄||7号線南北線': 'Namboku Line',
    '東京地下鉄||8号線有楽町線': 'Yurakucho Line',
    '東京地下鉄||9号線千代田線': 'Chiyoda Line',
    '東京臨海高速鉄道||りんかい線': 'Rinkai Line',
    '東京都||10号線新宿線': 'Shinjuku Line',
    '東京都||12号線大江戸線': 'Oedo Line',
    '東京都||1号線浅草線': 'Asakusa Line',
    '東京都||6号線三田線': 'Mita Line',
    '東京都||上野懸垂線': 'Ueno Zoo Monorail',
    '東京都||日暮里・舎人ライナー': 'Nippori-Toneri Liner',
    '東京都||荒川線': 'Arakawa Line',
    '東急電鉄||こどもの国線': 'Kodomonokuni Line',
    '東急電鉄||世田谷線': 'Setagaya Line',
    '東急電鉄||大井町線': 'Oimachi Line',
    '東急電鉄||東急多摩川線': 'Tokyu Tamagawa Line',
    '東急電鉄||東急新横浜線': 'Tokyu Shin-Yokohama Line',
    '東急電鉄||東横線': 'Toyoko Line',
    '東急電鉄||池上線': 'Ikegami Line',
    '東急電鉄||田園都市線': 'Den-en-toshi Line',
    '東急電鉄||目黒線': 'Meguro Line',
    '東日本旅客鉄道||上越新幹線': 'Joetsu Shinkansen',
    '東日本旅客鉄道||上越線': 'Joetsu Line',
    '東日本旅客鉄道||両毛線': 'Ryomo Line',
    '東日本旅客鉄道||中央線': 'Chuo Main Line',
    '東日本旅客鉄道||久留里線': 'Kururi Line',
    '東日本旅客鉄道||五日市線': 'Itsukaichi Line',
    '東日本旅客鉄道||五能線': 'Gono Line',
    '東日本旅客鉄道||京葉線': 'Keiyo Line',
    '東日本旅客鉄道||仙山線': 'Senzan Line',
    '東日本旅客鉄道||仙石線': 'Senseki Line',
    '東日本旅客鉄道||伊東線': 'Ito Line',
    '東日本旅客鉄道||信越線': "Shin'etsu Main Line",
    '東日本旅客鉄道||八戸線': 'Hachinohe Line',
    '東日本旅客鉄道||八高線': 'Hachiko Line',
    '東日本旅客鉄道||内房線': 'Uchibo Line',
    '東日本旅客鉄道||北上線': 'Kitakami Line',
    '東日本旅客鉄道||北陸新幹線': 'Hokuriku Shinkansen',
    '東日本旅客鉄道||南武線': 'Nambu Line',
    '東日本旅客鉄道||只見線': 'Tadami Line',
    '東日本旅客鉄道||吾妻線': 'Agatsuma Line',
    '東日本旅客鉄道||外房線': 'Sotobo Line',
    '東日本旅客鉄道||大湊線': 'Ominato Line',
    '東日本旅客鉄道||大糸線': 'Oito Line',
    '東日本旅客鉄道||大船渡線': 'Ofunato Line',
    '東日本旅客鉄道||奥羽線': 'Ou Main Line',
    '東日本旅客鉄道||小海線': 'Koumi Line',
    '東日本旅客鉄道||山手線': 'Yamanote Line',
    '東日本旅客鉄道||山田線': 'Yamada Line',
    '東日本旅客鉄道||川越線': 'Kawagoe Line',
    '東日本旅客鉄道||左沢線': 'Aterazawa Line',
    '東日本旅客鉄道||常磐線': 'Joban Line',
    '東日本旅客鉄道||弥彦線': 'Yahiko Line',
    '東日本旅客鉄道||成田線': 'Narita Line',
    '東日本旅客鉄道||日光線': 'Nikko Line',
    '東日本旅客鉄道||東北新幹線': 'Tohoku Shinkansen',
    '東日本旅客鉄道||東北線': 'Tohoku Main Line',
    '東日本旅客鉄道||東海道線': 'Tokaido Main Line',
    '東日本旅客鉄道||東金線': 'Togane Line',
    '東日本旅客鉄道||根岸線': 'Negishi Line',
    '東日本旅客鉄道||横浜線': 'Yokohama Line',
    '東日本旅客鉄道||横須賀線': 'Yokosuka Line',
    '東日本旅客鉄道||武蔵野線': 'Musashino Line',
    '東日本旅客鉄道||気仙沼線': 'Kesennuma Line',
    '東日本旅客鉄道||水戸線': 'Mito Line',
    '東日本旅客鉄道||水郡線': 'Suigun Line',
    '東日本旅客鉄道||津軽線': 'Tsugaru Line',
    '東日本旅客鉄道||烏山線': 'Karasuyama Line',
    '東日本旅客鉄道||田沢湖線': 'Tazawako Line',
    '東日本旅客鉄道||男鹿線': 'Oga Line',
    '東日本旅客鉄道||白新線': 'Hakushin Line',
    '東日本旅客鉄道||相模線': 'Sagami Line',
    '東日本旅客鉄道||石巻線': 'Ishinomaki Line',
    '東日本旅客鉄道||磐越東線': 'Banetsu East Line',
    '東日本旅客鉄道||磐越西線': 'Banetsu West Line',
    '東日本旅客鉄道||篠ノ井線': 'Shinonoi Line',
    '東日本旅客鉄道||米坂線': 'Yonesaka Line',
    '東日本旅客鉄道||総武線': 'Sobu Main Line',
    '東日本旅客鉄道||羽越線': 'Uetsu Main Line',
    '東日本旅客鉄道||花輪線': 'Hanawa Line',
    '東日本旅客鉄道||赤羽線': 'Akabane Line',
    '東日本旅客鉄道||越後線': 'Echigo Line',
    '東日本旅客鉄道||釜石線': 'Kamaishi Line',
    '東日本旅客鉄道||陸羽東線': 'Rikuu East Line',
    '東日本旅客鉄道||陸羽西線': 'Rikuu West Line',
    '東日本旅客鉄道||青梅線': 'Ome Line',
    '東日本旅客鉄道||飯山線': 'Iiyama Line',
    '東日本旅客鉄道||高崎線': 'Takasaki Line',
    '東日本旅客鉄道||鶴見線': 'Tsurumi Line',
    '東日本旅客鉄道||鹿島線': 'Kashima Line',
    '東武鉄道||亀戸線': 'Kameido Line',
    '東武鉄道||伊勢崎線': 'Isesaki Line',
    '東武鉄道||佐野線': 'Sano Line',
    '東武鉄道||大師線': 'Daishi Line',
    '東武鉄道||宇都宮線': 'Utsunomiya Line',
    '東武鉄道||小泉線': 'Koizumi Line',
    '東武鉄道||日光線': 'Nikko Line',
    '東武鉄道||東上本線': 'Tojo Main Line',
    '東武鉄道||桐生線': 'Kiryu Line',
    '東武鉄道||越生線': 'Ogose Line',
    '東武鉄道||野田線': 'Noda Line',
    '東武鉄道||鬼怒川線': 'Kinugawa Line',
    '東海交通事業||城北線': 'Johoku Line',
    '東海旅客鉄道||中央線': 'Chuo Main Line',
    '東海旅客鉄道||参宮線': 'Sangu Line',
    '東海旅客鉄道||名松線': 'Meisho Line',
    '東海旅客鉄道||太多線': 'Taita Line',
    '東海旅客鉄道||御殿場線': 'Gotemba Line',
    '東海旅客鉄道||東海道新幹線': 'Tokaido Shinkansen',
    '東海旅客鉄道||東海道線': 'Tokaido Main Line',
    '東海旅客鉄道||武豊線': 'Taketoyo Line',
    '東海旅客鉄道||紀勢線': 'Kisei Main Line',
    '東海旅客鉄道||身延線': 'Minobu Line',
    '東海旅客鉄道||関西線': 'Kansai Main Line',
    '東海旅客鉄道||飯田線': 'Iida Line',
    '東海旅客鉄道||高山線': 'Takayama Main Line',
    '東葉高速鉄道||東葉高速線': 'Toyo Rapid Line',
    '松浦鉄道||西九州線': 'Nishi-Kyushu Line',
    '横浜シーサイドライン||金沢シーサイドライン': 'Kanazawa Seaside Line',
    '横浜市||1号線・3号線': 'Blue Line',
    '横浜市||4号線': 'Green Line',
    '横浜高速鉄道||みなとみらい21線': 'Minatomirai Line',
    '樽見鉄道||樽見線': 'Tarumi Line',
    '比叡山鉄道||比叡山鉄道線': 'Sakamoto Cable',
    '水島臨海鉄道||水島本線': 'Mizushima Main Line',
    '水間鉄道||水間線': 'Mizuma Line',
    '江ノ島電鉄||江ノ島電鉄線': 'Enoshima Electric Railway Line',
    '沖縄都市モノレール||沖縄都市モノレール線': 'Okinawa Monorail Line',
    '泉北高速鉄道||泉北高速鉄道線': 'Semboku Line',
    '津軽鉄道||津軽鉄道線': 'Tsugaru Railway Line',
    '流鉄||流山線': 'Nagareyama Line',
    '湘南モノレール||江の島線': 'Enoshima Line',
    '熊本市||熊本市内軌道線': 'Kumamoto City Tram',
    '熊本電気鉄道||菊池線・藤崎線': 'Kikuchi Line / Fujisaki Line',
    '甘木鉄道||甘木線': 'Amagi Line',
    '由利高原鉄道||鳥海山ろく線': 'Chokai Sanroku Line',
    '皿倉登山鉄道||帆柱ケーブル線': 'Hobashira Cable Line',
    '相模鉄道||本線・いずみ野線': 'Sotetsu Main Line / Izumino Line',
    '真岡鐵道||真岡線': 'Moka Line',
    '神戸すまいまちづくり公社||摩耶ケーブル線': 'Maya Cable Line',
    '神戸市||海岸線': 'Kaigan Line',
    '神戸市||西神線・山手線・北神線': 'Seishin Line / Yamate Line / Hokushin Line',
    '神戸新交通||ポートアイランド線・六甲アイランド線': 'Port Island Line / Rokko Island Line',
    '神戸電鉄||三田線': 'Sanda Line',
    '神戸電鉄||公園都市線': 'Koen-toshi Line',
    '神戸電鉄||有馬線': 'Arima Line',
    '神戸電鉄||神戸高速線': 'Kobe Kosoku Line',
    '神戸電鉄||粟生線': 'Ao Line',
    '福井鉄道||福武線': 'Fukubu Line',
    '福岡市||空港線・箱崎線・七隈線': 'Airport Line / Hakozaki Line / Nanakuma Line',
    '福島交通||飯坂線': 'Iizaka Line',
    '秋田内陸縦貫鉄道||秋田内陸線': 'Akita Nairiku Line',
    '秩父鉄道||秩父本線': 'Chichibu Main Line',
    '立山黒部貫光||無軌条電車線': 'Tateyama Tunnel Trolleybus',
    '立山黒部貫光||鋼索線（立山）': 'Tateyama Cable Car',
    '立山黒部貫光||鋼索線（黒部）': 'Kurobe Cable Car',
    '筑波観光鉄道||筑波山鋼索鉄道線': 'Mt. Tsukuba Cable Car',
    '筑豊電気鉄道||筑豊電気鉄道線': 'Chikuho Electric Railroad Line',
    '箱根登山鉄道||鉄道線': 'Hakone Tozan Line',
    '箱根登山鉄道||鋼索線': 'Hakone Tozan Cable Car',
    '紀州鉄道||紀州鉄道線': 'Kishu Railway Line',
    '肥薩おれんじ鉄道||肥薩おれんじ鉄道線': 'Hisatsu Orange Railway Line',
    '能勢電鉄||妙見線': 'Myoken Line',
    '能勢電鉄||日生線': 'Nissei Line',
    '能勢電鉄||鋼索線': 'Myoken Cable Line',
    '舞浜リゾートライン||ディズニーリゾートライン': 'Disney Resort Line',
    '芝山鉄道||芝山鉄道線': 'Shibayama Railway Line',
    '若桜鉄道||若桜線': 'Wakasa Line',
    '西日本旅客鉄道||JR東西線': 'JR Tozai Line',
    '西日本旅客鉄道||おおさか東線': 'Osaka Higashi Line',
    '西日本旅客鉄道||七尾線': 'Nanao Line',
    '西日本旅客鉄道||伯備線': 'Hakubi Line',
    '西日本旅客鉄道||加古川線': 'Kakogawa Line',
    '西日本旅客鉄道||北陸新幹線': 'Hokuriku Shinkansen',
    '西日本旅客鉄道||北陸線': 'Hokuriku Main Line',
    '西日本旅客鉄道||博多南線': 'Hakata-Minami Line',
    '西日本旅客鉄道||可部線': 'Kabe Line',
    '西日本旅客鉄道||吉備線': 'Kibi Line',
    '西日本旅客鉄道||呉線': 'Kure Line',
    '西日本旅客鉄道||和歌山線': 'Wakayama Line',
    '西日本旅客鉄道||因美線': 'Inbi Line',
    '西日本旅客鉄道||城端線': 'Johana Line',
    '西日本旅客鉄道||境線': 'Sakai Line',
    '西日本旅客鉄道||大糸線': 'Oito Line',
    '西日本旅客鉄道||大阪環状線': 'Osaka Loop Line',
    '西日本旅客鉄道||奈良線': 'Nara Line',
    '西日本旅客鉄道||姫新線': 'Kishin Line',
    '西日本旅客鉄道||宇部線': 'Ube Line',
    '西日本旅客鉄道||宇野線': 'Uno Line',
    '西日本旅客鉄道||小浜線': 'Obama Line',
    '西日本旅客鉄道||小野田線': 'Onoda Line',
    '西日本旅客鉄道||山口線': 'Yamaguchi Line',
    '西日本旅客鉄道||山陰線': "San'in Main Line",
    '西日本旅客鉄道||山陽新幹線': 'Sanyo Shinkansen',
    '西日本旅客鉄道||山陽線': 'Sanyo Main Line',
    '西日本旅客鉄道||岩徳線': 'Gantoku Line',
    '西日本旅客鉄道||播但線': 'Bantan Line',
    '西日本旅客鉄道||木次線': 'Kisuki Line',
    '西日本旅客鉄道||本四備讃線': 'Honshi-Bisan Line',
    '西日本旅客鉄道||東海道線': 'Tokaido Main Line',
    '西日本旅客鉄道||桜井線': 'Sakurai Line',
    '西日本旅客鉄道||桜島線': 'Sakurajima Line',
    '西日本旅客鉄道||氷見線': 'Himi Line',
    '西日本旅客鉄道||津山線': 'Tsuyama Line',
    '西日本旅客鉄道||湖西線': 'Kosei Line',
    '西日本旅客鉄道||片町線': 'Katamachi Line',
    '西日本旅客鉄道||福塩線': 'Fukuen Line',
    '西日本旅客鉄道||福知山線': 'Fukuchiyama Line',
    '西日本旅客鉄道||紀勢線': 'Kisei Main Line',
    '西日本旅客鉄道||美祢線': 'Mine Line',
    '西日本旅客鉄道||舞鶴線': 'Maizuru Line',
    '西日本旅客鉄道||芸備線': 'Geibi Line',
    '西日本旅客鉄道||草津線': 'Kusatsu Line',
    '西日本旅客鉄道||赤穂線': 'Ako Line',
    '西日本旅客鉄道||越美北線': 'Etsumi-Hoku Line',
    '西日本旅客鉄道||関西空港線': 'Kansai Airport Line',
    '西日本旅客鉄道||関西線': 'Kansai Main Line',
    '西日本旅客鉄道||阪和線': 'Hanwa Line',
    '西日本旅客鉄道||高山線': 'Takayama Main Line',
    '西日本鉄道||天神大牟田線': 'Tenjin Omuta Line',
    '西日本鉄道||貝塚線': 'Kaizuka Line',
    '西武鉄道||多摩川線': 'Tamagawa Line',
    '西武鉄道||多摩湖線': 'Tamako Line',
    '西武鉄道||山口線': 'Yamaguchi Line',
    '西武鉄道||新宿線・拝島線': 'Shinjuku Line / Haijima Line',
    '西武鉄道||池袋線・西武秩父線': 'Ikebukuro Line / Seibu Chichibu Line',
    '豊橋鉄道||東田本線': 'Azumada Main Line',
    '豊橋鉄道||渥美線': 'Atsumi Line',
    '近江鉄道||本線・多賀線・八日市線': 'Ohmi Main Line / Taga Line / Yokaichi Line',
    '近畿日本鉄道||名古屋・三重線': 'Nagoya Line / Mie Lines',
    '近畿日本鉄道||大阪・京都・奈良線': 'Osaka Lines / Kyoto Line / Nara Lines',
    '近畿日本鉄道||生駒鋼索線': 'Ikoma Cable Line',
    '近畿日本鉄道||西信貴鋼索線': 'Nishi-Shigi Cable Line',
    '道南いさりび鉄道||道南いさりび鉄道線': 'South Hokkaido Railway Line',
    '遠州鉄道||鉄道線': 'Enshu Railway Line',
    '野岩鉄道||会津鬼怒川線': 'Aizu-Kinugawa Line',
    '銚子電気鉄道||銚子電気鉄道線': 'Choshi Electric Railway Line',
    '錦川鉄道||錦川清流線': 'Nishikigawa Seiryu Line',
    '長崎電気軌道||長崎市内軌道線': 'Nagasaki City Tram',
    '長良川鉄道||越美南線': 'Etsumi-Nan Line',
    '長野電鉄||長野線': 'Nagano Line',
    '関東鉄道||常総線': 'Joso Line',
    '関東鉄道||竜ヶ崎線': 'Ryugasaki Line',
    '阪堺電気軌道||阪堺線・上町線': 'Hankai Line / Uemachi Line',
    '阪急電鉄||京都線・千里線・嵐山線': 'Kyoto Line / Senri Line / Arashiyama Line',
    '阪急電鉄||神戸線・宝塚線・伊丹線': 'Kobe Line / Takarazuka Line / Itami Line',
    '阪急電鉄||神戸高速線': 'Kobe Kosoku Line',
    '阪神電気鉄道||本線・阪神なんば線': 'Hanshin Main Line / Hanshin Namba Line',
    '阪神電気鉄道||神戸高速線': 'Kobe Kosoku Line',
    '阿佐海岸鉄道||阿佐東線': 'Asato Line',
    '阿武隈急行||阿武隈急行線': 'Abukuma Express Line',
    '青い森鉄道||青い森鉄道線': 'Aoimori Railway Line',
    '青函トンネル記念館||青函トンネル竜飛斜坑線': 'Seikan Tunnel Tappi Incline',
    '静岡鉄道||静岡清水線': 'Shizuoka-Shimizu Line',
    '鞍馬寺||鞍馬山鋼索鉄道': 'Kurama-dera Cable',
    '養老鉄道||養老線': 'Yoro Line',
    '首都圏新都市鉄道||常磐新線': 'Tsukuba Express',
    '高尾登山電鉄||高尾鋼索線': 'Takao Cable Line',
    '高松琴平電気鉄道||琴平線・志度線・長尾線': 'Kotohira Line / Shido Line / Nagao Line',
    '鹿児島市||鹿児島市内軌道線': 'Kagoshima City Tram',
    '鹿島臨海鉄道||大洗鹿島線': 'Oarai-Kashima Line',
    '黒部峡谷鉄道||本線': 'Kurobe Gorge Main Line',
    # ── Meitetsu / Nankai branch lines (Nagoya / Osaka census stitch) ──
    '名古屋鉄道||三河線': 'Mikawa Line',
    '名古屋鉄道||各務原線': 'Kakamigahara Line',
    '名古屋鉄道||小牧線': 'Komaki Line',
    '名古屋鉄道||尾西線': 'Bisai Line',
    '名古屋鉄道||常滑線': 'Tokoname Line',
    '名古屋鉄道||広見線': 'Hiromi Line',
    '名古屋鉄道||河和線': 'Kowa Line',
    '名古屋鉄道||津島線': 'Tsushima Line',
    '名古屋鉄道||犬山線': 'Inuyama Line',
    '名古屋鉄道||知多新線': 'Chita New Line',
    '名古屋鉄道||空港線': 'Airport Line',
    '名古屋鉄道||竹鼻線': 'Takehana Line',
    '名古屋鉄道||蒲郡線': 'Gamagori Line',
    '名古屋鉄道||西尾線': 'Nishio Line',
    '名古屋鉄道||豊田線': 'Toyota Line',
    '南海電気鉄道||加太線': 'Kada Line',
    '南海電気鉄道||多奈川線': 'Tanagawa Line',
    '南海電気鉄道||空港線': 'Airport Line',
    '南海電気鉄道||高師浜線': 'Takashinohama Line',
    # ── JR line-name variants used by the ridership-bubble dataset ──
    '九州旅客鉄道||久大線': 'Kyudai Main Line',
    '九州旅客鉄道||日豊線': 'Nippo Main Line',
    '九州旅客鉄道||筑豊線': 'Chikuho Main Line',
    '九州旅客鉄道||豊肥線': 'Hohi Main Line',
    '九州旅客鉄道||長崎線': 'Nagasaki Main Line',
    '九州旅客鉄道||鹿児島線': 'Kagoshima Main Line',
    '北海道旅客鉄道||千歳線': 'Chitose Line',
    '北海道旅客鉄道||石勝線': 'Sekisho Line',
    # ── per-component / tram-route / numbered-subway lines (build_census v3) ──
    'とさでん交通||伊野線': 'Ino Line',
    'とさでん交通||後免線': 'Gomen Line',
    'とさでん交通||桟橋線': 'Sambashi Line',
    'とさでん交通||駅前線': 'Ekimae Line',
    '一般社団法人札幌市交通事業振興公社||1条線': 'Ichijo Line',
    '一般社団法人札幌市交通事業振興公社||山鼻線': 'Yamahana Line',
    '一般社団法人札幌市交通事業振興公社||山鼻西線': 'Yamahana-Nishi Line',
    '一般社団法人札幌市交通事業振興公社||都心線': 'Toshin Line',
    '一般財団法人青函トンネル記念館||青函トンネル竜飛斜坑線': 'Seikan Tunnel Tappi Incline',
    '万葉線||新湊港線': 'Shinminato-ko Line',
    '万葉線||高岡軌道線': 'Takaoka Tram Line',
    '三岐鉄道||近鉄連絡線': 'Kintetsu Connecting Line',
    '京王電鉄||動物園線': 'Dobutsuen Line',
    '京王電鉄||競馬場線': 'Keibajo Line',
    '京阪電気鉄道||交野線': 'Katano Line',
    '京阪電気鉄道||宇治線': 'Uji Line',
    '伊予鉄道||城北線': 'Johoku Line',
    '伊予鉄道||城南線': 'Jonan Line',
    '伊予鉄道||大手町線': 'Otemachi Line',
    '伊予鉄道||本町線': 'Honmachi Line',
    '伊予鉄道||花園線': 'Hanazono Line',
    '函館市||宝来・谷地頭線': 'Horai-Yachigashira Line',
    '函館市||本線': 'Hakodate Tram Main Line',
    '函館市||湯の川線': 'Yunokawa Line',
    '南海電気鉄道||和歌山港線': 'Wakayamako Line',
    '名古屋市||1号線東山線': 'Higashiyama Line',
    '名古屋市||2号線名城線': 'Meijo Line',
    '名古屋市||2号線名港線': 'Meiko Line',
    '名古屋市||3号線鶴舞線': 'Tsurumai Line',
    '名古屋市||4号線名城線': 'Meijo Line',
    '名古屋市||6号線桜通線': 'Sakura-dori Line',
    '名古屋鉄道||築港線': 'Chikko Line',
    '名古屋鉄道||羽島線': 'Hashima Line',
    '大阪モノレール||国際文化公園都市モノレール線（彩都線）': 'Saito Line',
    '富山地方鉄道||呉羽線': 'Kureha Line',
    '富山地方鉄道||安野屋線': 'Yasunoya Line',
    '富山地方鉄道||富山港線': 'Toyamako Line',
    '富山地方鉄道||富山都心線': 'Toyama City Loop Line',
    '富山地方鉄道||富山駅南北接続線': 'Toyama Station Connecting Line',
    '富山地方鉄道||支線': 'Branch Line',
    '広島電鉄||宇品線': 'Ujina Line',
    '広島電鉄||本線': 'Hiroden Main Line',
    '広島電鉄||横川線': 'Yokogawa Line',
    '広島電鉄||江波線': 'Eba Line',
    '広島電鉄||白島線': 'Hakushima Line',
    '広島電鉄||皆実線': 'Minami Line',
    '東京地下鉄||4号線丸ノ内線分岐線': 'Marunouchi Line Branch',
    '横浜市||1号線': 'Blue Line',
    '横浜市||3号線': 'Blue Line',
    '熊本市||上熊本線': 'Kami-Kumamoto Line',
    '熊本市||健軍線': 'Kengun Line',
    '熊本市||幹線': 'Kumamoto Tram Main Line',
    '熊本市||水前寺線': 'Suizenji Line',
    '熊本市||田崎線': 'Tasaki Line',
    '相模鉄道||相鉄新横浜線': 'Sotetsu Shin-Yokohama Line',
    '神戸市||西神延伸線': 'Seishin Extension Line',
    '福岡市||1号線(空港線)': 'Airport Line',
    '福岡市||2号線(箱崎線)': 'Hakozaki Line',
    '福岡市||3号線(七隈線)': 'Nanakuma Line',
    '立山黒部貫光||鋼索線': 'Tateyama Cable Car',
    '西日本鉄道||太宰府線': 'Dazaifu Line',
    '西日本鉄道||甘木線': 'Amagi Line',
    '西武鉄道||国分寺線': 'Kokubunji Line',
    '西武鉄道||狭山線': 'Sayama Line',
    '西武鉄道||西武園線': 'Seibuen Line',
    '西武鉄道||西武有楽町線': 'Seibu Yurakucho Line',
    '西武鉄道||豊島線': 'Toshima Line',
    '近畿日本鉄道||けいはんな線': 'Keihanna Line',
    '近畿日本鉄道||信貴線': 'Shigi Line',
    '近畿日本鉄道||南大阪線': 'Minami-Osaka Line',
    '近畿日本鉄道||吉野線': 'Yoshino Line',
    '近畿日本鉄道||天理線': 'Tenri Line',
    '近畿日本鉄道||山田線': 'Yamada Line',
    '近畿日本鉄道||御所線': 'Gose Line',
    '近畿日本鉄道||志摩線': 'Shima Line',
    '近畿日本鉄道||橿原線': 'Kashihara Line',
    '近畿日本鉄道||湯の山線': 'Yunoyama Line',
    '近畿日本鉄道||生駒線': 'Ikoma Line',
    '近畿日本鉄道||田原本線': 'Tawaramoto Line',
    '近畿日本鉄道||道明寺線': 'Domyoji Line',
    '近畿日本鉄道||鈴鹿線': 'Suzuka Line',
    '近畿日本鉄道||長野線': 'Nagano Line',
    '近畿日本鉄道||難波線': 'Namba Line',
    '近畿日本鉄道||鳥羽線': 'Toba Line',
    '長崎電気軌道||大浦支線': 'Oura Branch Line',
    '長崎電気軌道||本線': 'Nagasaki Tram Main Line',
    '長崎電気軌道||桜町支線': 'Sakuramachi Branch Line',
    '長崎電気軌道||蛍茶屋支線': 'Hotarujaya Branch Line',
    '長崎電気軌道||赤迫支線': 'Akasako Branch Line',
    '関西電力||関西電力': 'Kanden Tunnel Electric Bus',
    '阪急電鉄||今津線': 'Imazu Line',
    '阪急電鉄||甲陽線': 'Koyo Line',
    '阪急電鉄||箕面線': 'Mino Line',
    '阪神電気鉄道||武庫川線': 'Mukogawa Line',
    '鹿児島市||唐湊線': 'Toso Line',
    '鹿児島市||第一期線': 'Line 1',
    '鹿児島市||第二期線': 'Line 2',
    '鹿児島市||谷山線': 'Taniyama Line',
}


def _expand_bundles(table):
    """gtfs sometimes carries a ・-bundled line as one feature (京王線・高尾線・
    相模原線), sometimes as separate per-component features. Register every
    bundle's components individually too, so the table survives that change."""
    out = dict(table)
    for key, en in table.items():
        op, _, jp = key.partition('||')
        if '・' not in jp:
            continue
        jp_parts = [p if p.endswith('線') else p + '線'
                    for p in jp.split('・') if p]
        en_parts = [e.strip() for e in en.split(' / ')]
        if len(jp_parts) == len(en_parts):
            for jpp, enp in zip(jp_parts, en_parts):
                out.setdefault(op + '||' + jpp, enp)   # explicit entries win
    return out


LINES_EN = _expand_bundles(LINES_EN)

# ── segment remarks (free-text annotations from gtfs-gis.jp), keyed verbatim ──
# "incl." = 〜を含む (this throughput figure also covers that section/line);
# date notes give opening / closing / data-coverage caveats.
REMARKS_EN = {
    '競馬場線、動物園線を含む': 'incl. Keibajo Line, Dobutsuen Line',
    '愛知県、三重県内の各線': 'all lines within Aichi & Mie',
    '2022年度までは全線合計の数': 'through FY2022, figure is the whole-line total',
    '飾磨～山陽網干を含む': 'incl. Shikama–Sanyo-Aboshi',
    '交野線、宇治線を含む': 'incl. Katano Line, Uji Line',
    '大垣～旧新垂井～関ケ原、大垣～美濃赤坂を含む':
        'incl. Ogaki–old Shin-Tarui–Sekigahara, Ogaki–Mino-Akasaka',
    '天王寺駅～住吉を含む': 'incl. Tennoji-ekimae–Sumiyoshi',
    '西武有楽町線、豊島線、狭山線を含む':
        'incl. Seibu Yurakucho Line, Toshima Line, Sayama Line',
    '今津線、甲陽線、箕面線を含む': 'incl. Imazu Line, Koyo Line, Mino Line',
    '京都府、大阪府、奈良県内の各線': 'all lines within Kyoto, Osaka & Nara',
    '西武園線、国分寺線を含む': 'incl. Seibuen Line, Kokubunji Line',
    '武庫川線を含む': 'incl. Mukogawa Line',
    '中野坂上～方南町を含む': 'incl. Nakano-sakaue–Honancho',
    '西浦和～与野を含む': 'incl. Nishi-Urawa–Yono',
    '西桑名～阿下喜を含む': 'incl. Nishi-Kuwana–Ageki',
    '2019年度までは鳳～東羽衣を含む輸送密度':
        'through FY2019, density incl. Otori–Higashi-Hagoromo',
    '2019年度までは加茂～JR難波の輸送密度':
        'through FY2019, density for Kamo–JR-Namba',
    '市川塩浜～西船橋～南船橋を含む':
        'incl. Ichikawa-Shiohama–Nishi-Funabashi–Minami-Funabashi',
    '2019年度までは兵庫～和田岬を含む輸送密度':
        'through FY2019, density incl. Hyogo–Wadamisaki',
    '二俣川～湘南台を含む。2019年度途中から相鉄新横浜線を含む':
        'incl. Futamatagawa–Shonandai; from mid-FY2019, incl. Sotetsu Shin-Yokohama Line',
    '浅野～海芝浦、安善～大川を含む': 'incl. Asano–Umi-Shibaura, Anzen–Okawa',
    '2020年5月までは北神急行電鉄を含む輸送密度':
        'through May 2020, density incl. Hokushin Kyuko Railway',
    '井原～運動公園前を含む': 'incl. Ibara–Undokoen-mae',
    '北野白梅町～帷子ノ辻を含む': 'incl. Kitano-Hakubaicho–Katabiranotsuji',
    '錦糸町～御茶ノ水を含む': 'incl. Kinshicho–Ochanomizu',
    '日永～西日野を含む': 'incl. Hinaga–Nishi-Hino',
    '高宮～多賀大社前、八日市～近江八幡を含む':
        'incl. Takamiya–Taga-taisha-mae, Yokaichi–Omi-Hachiman',
    '住吉～マリンパークを含む': 'incl. Sumiyoshi–Marine Park',
    '品川～新川崎～鶴見、鶴見～羽沢横浜国大～東戸塚を含む':
        'incl. Shinagawa–Shin-Kawasaki–Tsurumi, Tsurumi–Hazawa-Yokohama-Kokudai–Higashi-Totsuka',
    '宝ヶ池～鞍馬を含む': 'incl. Takaragaike–Kurama',
    '御陵～びわ湖浜大津を含む': 'incl. Misasagi–Biwako-Hamaotsu',
    '2019年度以降は長万部～小樽の輸送密度':
        'from FY2019, density for Oshamambe–Otaru',
    '2024年3月16日開業': 'opened 16 Mar 2024',
    '2019年度までは米原～敦賀の輸送密度':
        'through FY2019, density for Maibara–Tsuruga',
    '2023年度は2024年3月15日までのデータ':
        'FY2023 figure covers data through 15 Mar 2024',
    '2019年度までは上郡～岡山の輸送密度':
        'through FY2019, density for Kamigori–Okayama',
    '2019年度までは厄神～谷川の輸送密度':
        'through FY2019, density for Yakujin–Tanikawa',
    '2019年度までは備後落合～三次の輸送密度':
        'through FY2019, density for Bingo-Ochiai–Miyoshi',
    '2019年度までは宍道～備後落合の輸送密度':
        'through FY2019, density for Shinji–Bingo-Ochiai',
    '2023年度はしなの鉄道線・北しなの線合算の数':
        'FY2023 figure combines Shinano Railway Line & Kita-Shinano Line',
    '砂原線をふくむ': 'incl. Sunahara Line',
    '2020年5月7日廃止': 'closed 7 May 2020',
    '南千歳～新千歳空港を含む': 'incl. Minami-Chitose–New Chitose Airport',
    '2021年4月1日廃止': 'closed 1 Apr 2021',
    '2022年度以前は深川～留萌の輸送密度':
        'before FY2022, density for Fukagawa–Rumoi',
    '2023年4月1日廃止。深川～留萌の輸送密度':
        'closed 1 Apr 2023; density for Fukagawa–Rumoi',
    '日暮里～尾久～赤羽、赤羽～武蔵浦和～大宮を含む':
        'incl. Nippori–Oku–Akabane, Akabane–Musashi-Urawa–Omiya',
    '松島～高城町を含む': 'incl. Matsushima–Takagimachi',
    '2019年度までは神戸～姫路を含む輸送密度':
        'through FY2019, density incl. Kobe–Himeji',
    '2019年度までは三次～狩留家の輸送密度':
        'through FY2019, density for Miyoshi–Karuga',
    '2019年度までは狩留家～広島の輸送密度':
        'through FY2019, density for Karuga–Hiroshima',
    '雀田～長門本山を含む': 'incl. Suzuta–Nagato-Motoyama',
    '長門市～仙崎を含む': 'incl. Nagatoshi–Senzaki',
    '2019年度までは天王寺～日根野を含む輸送密度':
        'through FY2019, density incl. Tennoji–Hineno',
    '海線': 'coastal route',
    '2020年度までは牟岐～海部の輸送密度':
        'through FY2020, density for Mugi–Kaifu',
    '2020年度までは牟岐～海部の輸送密度。2020年11月30日運行休止':
        'through FY2020, density for Mugi–Kaifu; service suspended 30 Nov 2020',
    '長与経由': 'via Nagayo',
    '2022年9月23日開業': 'opened 23 Sep 2022',
    '2019年度までは札幌市': 'through FY2019, operated by the City of Sapporo',
    '谷地頭～十字街を含む': 'incl. Yachigashira–Jujigai',
    '八木山動物公園～荒井を含む': 'incl. Yagiyama-Dobutsukoen–Arai',
    '2019年度までは富山地方鉄道と富山ライトレールを合算したもの':
        'through FY2019, combined Toyama Chiho Railway & Toyama Light Rail',
    '2023年度は2024年3月16日以降の金沢～大聖寺の輸送量も含めて金沢～倶利伽羅の営業キロで割っている':
        'FY2023: also includes Kanazawa–Daishoji traffic from 16 Mar 2024, '
        'divided by the Kanazawa–Kurikara route length',
    '2023年8月26日開業': 'opened 26 Aug 2023',
    '太田～東小泉を含む': 'incl. Ota–Higashi-Koizumi',
    '2023年3月18日開業': 'opened 18 Mar 2023',
    '2019年11月1日から休止': 'suspended from 1 Nov 2019',
    '2021年度までは富士急行': 'through FY2021, operated by Fuji Kyuko',
    '千葉～県庁前を含む': 'incl. Chiba–Kenchomae',
    '2021年11月までは伊豆箱根鉄道': 'through Nov 2021, operated by Izuhakone Railway',
    '福井口～三国港を含む': 'incl. Fukui-guchi–Mikuni-minato',
    '福井城址大名町～福井駅を含む': 'incl. Fukui-Joshi-Daimyomachi–Fukui Station',
    '西舞鶴～豊岡を含む': 'incl. Nishi-Maizuru–Toyooka',
    '2023年度データなし': 'no FY2023 data',
    '川跡～出雲大社前を含む': 'incl. Kawato–Izumo-Taisha-mae',
    '柳川～清輝橋を含む': 'incl. Yanagawa–Seikibashi',
    '瓦町～琴電志度、瓦町～長尾を含む':
        'incl. Kawaramachi–Kotoden-Shido, Kawaramachi–Nagao',
    '松山市～郡中港を含む': 'incl. Matsuyamashi–Gunchu-ko',
    '御免～奈半利を含む': 'incl. Gomen–Nahari',
    '2021年12月24日までは海部～甲浦': 'through 24 Dec 2021, Kaifu–Kannoura',
    '中洲川端～貝塚、橋本～天神南を含む':
        'incl. Nakasu-Kawabata–Kaizuka, Hashimoto–Tenjin-Minami',
    '金田～田川後藤寺を含む': 'incl. Kanada–Tagawa-Gotoji',
    '上熊本～北熊本を含む': 'incl. Kami-Kumamoto–Kita-Kumamoto',
    '首里～てだこ浦西（4.1キロ）は2019年10月開業':
        'Shuri–Tedako-Uranishi (4.1 km) opened Oct 2019',
}

# ── stations OSM doesn't carry: abolished, renamed, funiculars, cable cars ──
STATIONS_MANUAL = {
    'IRいしかわ鉄道||?利伽羅': 'Kurikara',
    'あいの風とやま鉄道||?利伽羅': 'Kurikara',
    'ゆりかもめ||国際展示場正門': 'Kokusai-Tenjijo-Seimon',
    'ゆりかもめ||船の科学館': 'Fune-no-Kagakukan',
    'スカイレールサービス||みどり中央': 'Midori-chuo',
    'スカイレールサービス||みどり口': 'Midoriguchi',
    'ラクテンチ||雲泉寺': 'Unsenji',
    '万葉線||越ノ潟': 'Koshinokata',
    '万葉線||高岡駅': 'Takaoka Station',
    '九州旅客鉄道||佐賀': 'Saga',
    '京成電鉄||押上': 'Oshiage',
    '京浜急行電鉄||仲木戸': 'Nakakido',
    '京浜急行電鉄||新逗子': 'Shin-Zushi',
    '京浜急行電鉄||産業道路': 'Sangyo-doro',
    '京浜急行電鉄||羽田空港国内線ターミナル': 'Haneda Airport Domestic Terminal',
    '京浜急行電鉄||羽田空港国際線ターミナル': 'Haneda Airport International Terminal',
    '京浜急行電鉄||花月園前': 'Kagetsuen-mae',
    '京阪電気鉄道||ケーブル八幡宮口': 'Cable Hachimangu-guchi',
    '京阪電気鉄道||ケーブル八幡宮山上': 'Cable Hachimangu-sanjo',
    '伊豆箱根鉄道||富士フィルム前': 'Fujifilm-mae',
    '函館市||函館どつく前': 'Hakodate-dokku-mae',
    '函館市||湯の川': 'Yunokawa',
    '北海道旅客鉄道||新十津川': 'Shin-Totsukawa',
    '北海道旅客鉄道||様似': 'Samani',
    '北海道旅客鉄道||留萌': 'Rumoi',
    '北海道旅客鉄道||石狩沼田': 'Ishikari-Numata',
    '名古屋ガイドウェイバス||小幡緑地': 'Obata-ryokuchi',
    '名古屋市||中村区役所': 'Nakamura-kuyakusho',
    '四国ケーブル||八栗山上': 'Yakuri-sanjo',
    '四国ケーブル||八栗登山口': 'Yakuri-tozanguchi',
    '大山観光電鉄||阿夫利神社': 'Afuri-jinja',
    '宇都宮ライトレール||宇都宮駅東口': 'Utsunomiya Station East',
    '宇都宮ライトレール||芳賀・高根沢工業団地': 'Haga-Takanezawa Industrial Park',
    '岡山電気軌道||おかでんミュージアム': 'Okaden Museum',
    '岡山電気軌道||岡山駅前': 'Okayama Station',
    '嵯峨野観光鉄道||トロッコ亀岡': 'Torokko Kameoka',
    '広島電鉄||広電西広島（己斐）': 'Hiroden-Nishi-Hiroshima',
    '弘南鉄道||弘前中央': 'Hirosaki-chuo',
    '東京モノレール||羽田空港国際線ビル': 'Haneda Airport International Terminal',
    '東京モノレール||羽田空港第1ビル': 'Haneda Airport Terminal 1',
    '東京モノレール||羽田空港第2ビル': 'Haneda Airport Terminal 2',
    '東京地下鉄||二重橋前': 'Nijubashimae',
    '東京地下鉄||押上': 'Oshiage',
    '東京地下鉄||明治神宮前': 'Meiji-jingumae',
    '東京都||上野動物園東園': 'Ueno Zoo East',
    '東京都||上野動物園西園': 'Ueno Zoo West',
    '東京都||押上': 'Oshiage',
    '東急電鉄||南町田': 'Minami-machida',
    '東武鉄道||押上': 'Oshiage',
    '東武鉄道||松原団地': 'Matsubara-danchi',
    '皿倉登山鉄道||山上': 'Sanjo',
    '皿倉登山鉄道||山麓': 'Sanroku',
    '神戸すまいまちづくり公社||虹': 'Niji',
    '福井鉄道||越前武生': 'Echizen-Takefu',
    '秩父鉄道||上熊谷': 'Kami-Kumagaya',
    '立山黒部貫光||大観峰': 'Daikanbo',
    '立山黒部貫光||室堂': 'Murodo',
    '能勢電鉄||ケーブル山上': 'Cable Sanjo',
    '能勢電鉄||川西能勢口': 'Kawanishi-Noseguchi',
    '西武鉄道||西武遊園地': 'Seibu-Yuenchi',
    '豊橋鉄道||赤岩口': 'Akaiwaguchi',
    '豊橋鉄道||駅前': 'Ekimae',
    '阪堺電気軌道||浜寺駅前': 'Hamadera-ekimae',
    '阿佐海岸鉄道||甲浦': 'Kannoura',
    '鞍馬寺||多宝塔': 'Tahoto',
    '鞍馬寺||山門': 'Sanmon',
    '南海電気鉄道||浜寺公園': 'Hamadera-koen',
    '南海電気鉄道||諏訪ノ森': 'Suwanomori',
    '南海電気鉄道||高石': 'Takaishi',
    '名古屋ガイドウェイバス||川宮': 'Kawamiya',
    '名古屋ガイドウェイバス||白沢渓谷': 'Shirasawa-keikoku',
    '名古屋ガイドウェイバス||金屋': 'Kanaya',
    '西日本旅客鉄道||大和新庄': 'Yamato-Shinjo',
    '阪堺電気軌道||天王寺駅前': 'Tennoji-ekimae',
    '阪急電鉄||川西能勢口': 'Kawanishi-Noseguchi',
    # rural / BRT-converted JR stops OSM maps as ways (this node query misses them)
    '九州旅客鉄道||下ノ江': 'Shitanoe',
    '九州旅客鉄道||今山': 'Imayama',
    '九州旅客鉄道||大行司': 'Daigyoji',
    '九州旅客鉄道||大鶴': 'Otsuru',
    '九州旅客鉄道||宝珠山': 'Hoshuyama',
    '九州旅客鉄道||彦山': 'Hikosan',
    '九州旅客鉄道||歓遊舎ひこさん': "Kan'yusha-Hikosan",
    '九州旅客鉄道||筑前岩屋': 'Chikuzen-Iwaya',
    '九州旅客鉄道||肥前山口': 'Hizen-Yamaguchi',
    '九州旅客鉄道||豊前桝田': 'Buzen-Masuda',
    '九州旅客鉄道||鹿家': 'Shikaka',
    '北海道旅客鉄道||下金山': 'Shimo-Kanayama',
    '北海道旅客鉄道||中ノ沢': 'Nakanosawa',
    '北海道旅客鉄道||二股': 'Futamata',
    '北海道旅客鉄道||仁山': 'Niyama',
    '北海道旅客鉄道||初野': 'Hatsuno',
    '北海道旅客鉄道||北秩父別': 'Kita-Chippubetsu',
    '北海道旅客鉄道||南幌延': 'Minami-Horonobe',
    '北海道旅客鉄道||名寄高校': 'Nayoro-Koko',
    '北海道旅客鉄道||山部': 'Yamabe',
    '北海道旅客鉄道||布部': 'Nunobe',
    '北海道旅客鉄道||幾寅': 'Ikutora',
    '北海道旅客鉄道||恩根内': 'Onnenai',
    '北海道旅客鉄道||恵比島': 'Ebishima',
    '北海道旅客鉄道||愛山': 'Aizan',
    '北海道旅客鉄道||抜海': 'Bakkai',
    '北海道旅客鉄道||東滝川': 'Higashi-Takikawa',
    '北海道旅客鉄道||東鹿越': 'Higashi-Shikagoe',
    '北海道旅客鉄道||浜田浦': 'Hamataura',
    '北海道旅客鉄道||滝ノ上': 'Takinoue',
    '北海道旅客鉄道||真布': 'Mappu',
    '北海道旅客鉄道||秩父別': 'Chippubetsu',
    '名古屋鉄道||吉良吉田': 'Kira-Yoshida',
    '名古屋鉄道||西尾口': 'Nishioguchi',
    '四国旅客鉄道||八十場': 'Yasoba',
    '東日本旅客鉄道||姨捨': 'Obasute',
    '東日本旅客鉄道||鷹ノ巣': 'Takanosu',
    '東海旅客鉄道||飛騨一ノ宮': 'Hida-Ichinomiya',
    '東海旅客鉄道||飛騨古川': 'Hida-Furukawa',
    '東海旅客鉄道||飛騨国府': 'Hida-Kokufu',
    '東海旅客鉄道||飛騨宮田': 'Hida-Miyata',
    '東海旅客鉄道||飛騨細江': 'Hida-Hosoe',
    '東海旅客鉄道||飛騨萩原': 'Hida-Hagiwara',
    '西日本旅客鉄道||木次': 'Kisuki',
    # ── tram / local stops OSM has no name:en for ──
    'しなの鉄道||テクノさかき': 'Techno-Sakaki',
    'しなの鉄道||田中': 'Tanaka',
    'とさでん交通||文珠通': 'Monjudori',
    'とさでん交通||田辺島通': 'Tanabejimadori',
    'ひたちなか海浜鉄道||工機前': 'Koki-mae',
    'スカイレールサービス||みどり中街': 'Midori-nakagai',
    '万葉線||中伏木': 'Naka-Fushiki',
    '万葉線||中新湊': 'Naka-Shinminato',
    '万葉線||六渡寺': 'Rokudoji',
    '万葉線||吉久': 'Yoshihisa',
    '万葉線||坂下町': 'Sakashitamachi',
    '万葉線||市民病院前': 'Shimin-byoin-mae',
    '万葉線||庄川口': 'Shogawaguchi',
    '万葉線||志貴野中学校前': 'Shikino-chugakko-mae',
    '万葉線||急患医療センター前': 'Kyukan-iryo-center-mae',
    '万葉線||新吉久': 'Shin-Yoshihisa',
    '万葉線||新町口': 'Shimmachiguchi',
    '万葉線||新能町': 'Shin-Nomachi',
    '万葉線||東新湊': 'Higashi-Shinminato',
    '万葉線||江尻': 'Ejiri',
    '万葉線||海王丸': 'Kaiomaru',
    '万葉線||米島口': 'Yoneshimaguchi',
    '万葉線||能町口': 'Nomachiguchi',
    '万葉線||荻布': 'Ogino',
    '万葉線||西新湊': 'Nishi-Shinminato',
    '伊予鉄道||平和通一丁目': 'Heiwadori 1-chome',
    '伊予鉄道||本町三丁目': 'Honmachi 3-chome',
    '伊予鉄道||本町五丁目': 'Honmachi 5-chome',
    '伊予鉄道||本町六丁目': 'Honmachi 6-chome',
    '伊予鉄道||本町四丁目': 'Honmachi 4-chome',
    '伊予鉄道||松山市駅': 'Matsuyamashi Station',
    '伊予鉄道||萱町六丁目': 'Kayamachi 6-chome',
    '伊予鉄道||道後公園': 'Dogo-koen',
    '名古屋市||伝馬町': 'Tenmacho',
    '名古屋市||神宮西': 'Jingu-nishi',
    '天竜浜名湖鉄道||天竜二俣': 'Tenryu-Futamata',
    '富山地方鉄道||オークスカナルパークホテル富山前': 'Oaks Canal Park Hotel Toyama-mae',
    '富山地方鉄道||グランドプラザ前': 'Grand Plaza-mae',
    '富山地方鉄道||上本町': 'Kami-Honmachi',
    '富山地方鉄道||中町（西町北）': 'Nakamachi',
    '富山地方鉄道||南富山駅前': 'Minami-Toyama-ekimae',
    '富山地方鉄道||地鉄ビル前': 'Chitetsu Building-mae',
    '富山地方鉄道||堀川小泉': 'Horikawa-Koizumi',
    '富山地方鉄道||大手モール': 'Ote Mall',
    '富山地方鉄道||広貫堂前': 'Kokando-mae',
    '富山地方鉄道||荒町': 'Aramachi',
    '富山地方鉄道||西中野': 'Nishi-Nakano',
    '富山地方鉄道||西町': 'Nishicho',
    '富山地方鉄道||諏訪川原': 'Suwagawara',
    '富山地方鉄道||電気ビル前': 'Denki Building-mae',
    '富山地方鉄道||龍谷富山高校前（永楽町）': 'Ryukoku-Toyama-Koko-mae',
    '岡山電気軌道||東山・おかでんミュージアム': 'Higashiyama / Okaden Museum',
    '嵯峨野観光鉄道||トロッコ保津峡': 'Torokko Hozukyo',
    '嵯峨野観光鉄道||トロッコ嵐山': 'Torokko Arashiyama',
    '広島電鉄||宇品三丁目': 'Ujina 3-chome',
    '広島電鉄||宇品二丁目': 'Ujina 2-chome',
    '広島電鉄||宇品五丁目': 'Ujina 5-chome',
    '広島電鉄||宇品四丁目': 'Ujina 4-chome',
    '広島電鉄||廿日市市役所前（平良）': 'Hatsukaichi-shiyakusho-mae',
    '広島電鉄||横川一丁目': 'Yokogawa 1-chome',
    '広島電鉄||段原一丁目': 'Danbara 1-chome',
    '広島電鉄||猿猴橋町': 'Enkobashi-cho',
    '広島電鉄||皆実町二丁目': 'Minamimachi 2-chome',
    '広島電鉄||皆実町六丁目': 'Minamimachi 6-chome',
    '広島高速交通||祇園新橋北': 'Gion-Shimbashi-kita',
    '智頭急行||宮本武蔵': 'Miyamoto-Musashi',
    '智頭急行||平福': 'Hirafuku',
    '津軽鉄道||五農校前': 'Gonoko-mae',
    '熊本市||動植物園入口': 'Doshokubutsuen-iriguchi',
    '熊本市||祇園橋': 'Gionbashi',
    '福井鉄道||スポーツ公園': 'Sports Park',
    '福井鉄道||清明': 'Seimei',
    '秩父鉄道||ソシオ流通センター': 'Socio Ryutsu Center',
    '西日本鉄道||試験場前': 'Shikenjo-mae',
    '遠州鉄道||浜北': 'Hamakita',
    '長崎電気軌道||八千代町': 'Yachiyomachi',
    '長崎電気軌道||大浦海岸通': 'Oura-kaigandori',
    '長崎電気軌道||市民会館': 'Shimin-kaikan',
    '長崎電気軌道||銭座町': 'Zenzamachi',
    '関西電力||黒部ダム': 'Kurobe Dam',
    '高松琴平電気鉄道||井戸': 'Ido',
    '高松琴平電気鉄道||学園通り': 'Gakuendori',
    '高松琴平電気鉄道||平木': 'Hiraki',
    '高松琴平電気鉄道||木太東口': 'Kita-Higashiguchi',
    '高松琴平電気鉄道||林道': 'Rindo',
    '高松琴平電気鉄道||池戸': 'Ikenobe',
    '高松琴平電気鉄道||西前田': 'Nishi-Maeda',
    '高松琴平電気鉄道||農学部前': 'Nogakubu-mae',
}

# ──────────────────────────────── helpers ──────────────────────────────────
MACRONS = {'ā': 'a', 'ī': 'i', 'ū': 'u', 'ē': 'e', 'ō': 'o',
           'â': 'a', 'î': 'i', 'û': 'u', 'ê': 'e', 'ô': 'o',
           'Ā': 'A', 'Ī': 'I', 'Ū': 'U', 'Ē': 'E', 'Ō': 'O',
           'Â': 'A', 'Î': 'I', 'Û': 'U', 'Ê': 'E', 'Ô': 'O'}


def clean_en(s):
    """OSM name:en -> plain-ASCII station label."""
    for k, v in MACRONS.items():
        s = s.replace(k, v)
    s = re.sub(r'\s*\(.*?\)\s*', ' ', s)        # drop parenthetical notes
    s = re.sub(r'\s+[Ss]tation$', '', s)        # drop trailing " Station"
    return ' '.join(s.split()).strip()


def norm(s):
    """Normalise a Japanese station name for matching: fullwidth->halfwidth,
    drop bracketed sub-names, and unify the ヶ/ケ and small-tsu variants that
    differ between sources."""
    s = unicodedata.normalize('NFKC', s)
    s = re.sub(r'[(〈《].*?[)〉》]', '', s)        # 諫早（雲仙・島原口） → 諫早
    return (s.replace('ヶ', 'ケ').replace('ヵ', 'カ')
             .replace('ッ', 'ツ').replace('・', '').replace(' ', ''))


def ends(geom):
    t, c = geom['type'], geom['coordinates']
    return (c[0], c[-1]) if t == 'LineString' else (c[0][0], c[-1][-1])


# ──────────────────────────────── build ────────────────────────────────────
def main():
    fc = json.load(open(HERE + '/data/segments.geojson', encoding='utf-8'))
    osm = json.load(open(HERE + '/data/osm_jp_stations.json', encoding='utf-8'))['elements']

    # OSM stations grouped by normalised Japanese name
    by_name = defaultdict(list)
    for e in osm:
        t = e.get('tags', {})
        nm, en = t.get('name'), t.get('name:en')
        if nm and en:
            by_name[norm(nm)].append((e['lat'], e['lon'], clean_en(en)))

    # one robust coordinate per (op, station): median of all observed points
    obs = defaultdict(list)
    for f in fc['features']:
        p = f['properties']
        a, b = ends(f['geometry'])
        for nm, c in ((p['from'], a), (p['to'], b)):
            if nm:
                obs[(p['op'], nm)].append(c)
    # the JR ridership bubbles carry intermediate stations the coarse national
    # segments omit — fold them in so every bubble gets an English name too
    sfc_path = HERE + '/data/stations.geojson'
    bubble_ops, bubble_lines = set(), set()
    if os.path.exists(sfc_path):
        for f in json.load(open(sfc_path, encoding='utf-8'))['features']:
            p = f['properties']
            bubble_ops.add(p['op'])
            bubble_lines.add(p['op'] + '||' + p['line'])
            if p.get('station'):
                obs[(p['op'], p['station'])].append(f['geometry']['coordinates'])
    coord = {k: (statistics.median(x[0] for x in v),
                 statistics.median(x[1] for x in v)) for k, v in obs.items()}

    stations, ambiguous, unmatched = {}, [], []
    for (op, nm), (lon, lat) in coord.items():
        cands = by_name.get(norm(nm))
        if not cands:
            if (op + '||' + nm) in STATIONS_MANUAL:
                stations[op + '||' + nm] = STATIONS_MANUAL[op + '||' + nm]
            else:
                unmatched.append((op, nm))
            continue
        ens = {c[2] for c in cands}
        if len(ens) == 1:
            stations[op + '||' + nm] = cands[0][2]
        else:
            best = min(cands, key=lambda c: math.hypot(c[0] - lat, c[1] - lon))
            stations[op + '||' + nm] = best[2]
            ambiguous.append((op, nm, best[2], sorted(ens)))

    # cover lines / operators / remarks actually present, and warn on any gap
    op_present = sorted({f['properties']['op'] for f in fc['features']} | bubble_ops)
    ln_present = sorted({f['properties']['op'] + '||' + f['properties']['line']
                         for f in fc['features']} | bubble_lines)
    rm_present = sorted({f['properties'].get('remark', '') for f in fc['features']}
                        - {''})
    operators = {o: OPERATORS_EN[o] for o in op_present if o in OPERATORS_EN}
    lines = {k: LINES_EN[k] for k in ln_present if k in LINES_EN}
    remarks = {r: REMARKS_EN[r] for r in rm_present if r in REMARKS_EN}

    out = {'operators': operators, 'lines': lines,
           'stations': stations, 'remarks': remarks}
    json.dump(out, open(HERE + '/data/names_en.json', 'w', encoding='utf-8'),
              ensure_ascii=False, separators=(',', ':'), sort_keys=True)

    print('names_en.json written')
    print(f'  operators : {len(operators)}/{len(op_present)}'
          + ('' if len(operators) == len(op_present) else '  *** MISSING ***'))
    print(f'  lines     : {len(lines)}/{len(ln_present)}'
          + ('' if len(lines) == len(ln_present) else '  *** MISSING ***'))
    print(f'  remarks   : {len(remarks)}/{len(rm_present)}'
          + ('' if len(remarks) == len(rm_present) else '  *** MISSING ***'))
    print(f'  stations  : {len(stations)}/{len(coord)} '
          f'({100 * len(stations) // len(coord)}%)  '
          f'[{len(ambiguous)} disambiguated by coord]')
    for o in op_present:
        if o not in OPERATORS_EN:
            print('  MISSING operator:', o)
    for k in ln_present:
        if k not in LINES_EN:
            print('  MISSING line:', k)
    for r in rm_present:
        if r not in REMARKS_EN:
            print('  MISSING remark:', r)
    if unmatched:
        print(f'  {len(unmatched)} unmatched stations (fall back to Japanese):')
        for op, nm in sorted(unmatched):
            print(f'      {op}||{nm}')


if __name__ == '__main__':
    main()
