"""
US Religion Census 2020 (ASARB) group code -> taxonomy leaf.

372 bodies plus a Totals row. Mapped by group CODE, never by name: "Orthodox" appears in
this file across Eastern Orthodoxy, Orthodox Judaism, the Orthodox Presbyterian Church, the
Orthodox Anglican Church, the Orthodox Mennonite Church and the Orthodox Old Roman Catholic
Communion — six unrelated families (spec.md §2.3).

Leaf ids are short slugs under a branch from branches.py. The branch must already exist;
build_tree.py fails if it does not, which is the guard against silent node creation.

REVIEW holds the calls that are genuinely arguable, with the reason. UNMAPPED holds
categories that are not religious affiliations at all and are deliberately not on the tree.
"""

# Categories held off the tree entirely — spec.md §2.3.
UNMAPPED = {
    "896": "Hindu Yoga and Meditation — 437,115 'adherents' in 396 counties. Not a "
           "religious body and not an affiliation: these are yoga and meditation centres. "
           "Folding it into hinduism would double count against Hindu Temples (895) and "
           "assert something false about 437k people. Anita's call to make explicitly.",
}

# Placements that are defensible but arguable. Every one of these is a real decision,
# not a gap — recorded so the reasoning is not lost and can be overturned on purpose.
REVIEW = {
    "437": "Union of Messianic Jewish Congregations -> christianity.messianic. See the "
           "branch note: Christian theology, Jewish self-description.",
    "058": "Association of Messianic Congregations -> christianity.messianic. Same.",
    "C22": "Church of God and Saints of Christ -> hebrewisraelite. Oldest Black Hebrew "
           "body (1896), keeps Christian elements. Neither Judaism nor plainly Christian.",
    "232": "Full Gospel Baptist Church Fellowship -> pentecostal.trinitarian. Baptist in "
           "name and polity, charismatic in practice; founded 1994 out of Black Baptist "
           "churches adopting Pentecostal worship. Could equally sit under baptist.",
    "291": "Missionary Church -> anabaptist.mennonite. Origin is Mennonite Brethren in "
           "Christ; present identity is broadly evangelical/holiness.",
    "073": "Bible Fellowship Church -> anabaptist.mennonite. Same shape as 291.",
    "211": "Fellowship of Evangelical Bible Churches -> anabaptist.mennonite. Formerly "
           "Evangelical Mennonite Brethren.",
    "213": "Fellowship of Evangelical Churches -> anabaptist.mennonite. Formerly "
           "Evangelical Mennonite Church.",
    "070": "Bruderhof -> anabaptist.hutterite. Communal and Anabaptist, was in and out of "
           "communion with the Hutterites; not a Hutterite Leut.",
    "FFL": "Knanaya Churches -> oriental. The Knanaya are an endogamous community split "
           "across Syro-Malabar Catholic and Syriac Orthodox jurisdictions; ASARB gives "
           "one row, so it cannot be resolved to the right side of that line here.",
    "F28": "Malankara Mar Thoma -> oriental. Reformed Oriental, in communion with the "
           "Anglicans; sits between oriental and anglican by any reading.",
    "F13": "'Church of Christ', 19 congregations -> restorationist. The bare name is "
           "ambiguous and may be a Latter Day Saint body (Temple Lot). NEEDS CHECKING.",
    "F53": "'Church of God', 204 congregations -> pentecostal.trinitarian. Bare name, "
           "several bodies use it. NEEDS CHECKING.",
    "F16": "Church of God of the Firstborn -> pentecostal.oneness. Low confidence.",
    "FHJ": "Agape Christian Fellowship -> anabaptist.mennonite. Appears among the "
           "Mennonite groups in ASARB's own ordering; low confidence.",
    "FFS": "Anabaptist Disciples of Christ -> anabaptist.mennonite. Low confidence.",
    "FEZ": "Believers in Christ -> anabaptist.mennonite. Low confidence.",
    "FF1": "Christian Communities -> anabaptist.mennonite. Low confidence.",
    "FHP": "Nazarene Christian Congregation -> anabaptist.apostolic. Apostolic Christian "
           "(Nazarean) related, not Church of the Nazarene.",
    "171": "Churches of God General Conference -> holiness. The Winebrenner body, German "
           "Reformed in origin, holiness in practice.",
    "051": "Armenian Evangelical Churches -> reformed.congregational. Congregational "
           "polity, Armenian ethnic body; not Oriental Orthodox.",
    "462": "Vedanta Society -> hinduism. A Hindu missionary order in the West rather than "
           "a temple congregation.",
    "895": "Hindu Temples -> hinduism. The unit is temples, not people; ASARB's adherent "
           "figure here is a compiler estimate (spec.md §3.1).",
    "267": "Muslim Estimate -> islam. Named an estimate by ASARB itself. No internal "
           "detail, so Sunni/Shia/Ahmadi are invisible in the US on this source.",
}

MAP = {
    # ---------------------------------------------------------------- Catholic
    "081": "christianity.catholic.latin.catholic-church",
    "352": "christianity.catholic.independent.pncc",
    "315": "christianity.catholic.independent.naorcc",
    "FFP": "christianity.catholic.independent.ecc-communion",
    "FGK": "christianity.catholic.independent.ecc",
    "439": "christianity.catholic.independent.united-catholic",
    "D66": "christianity.catholic.independent.liberal",
    "FFM": "christianity.catholic.independent.cacina",
    "FFN": "christianity.catholic.independent.oorcc",

    # ---------------------------------------------------------------- Eastern Orthodox
    "246": "christianity.orthodox.canonical.greek",
    "331": "christianity.orthodox.canonical.oca",
    "034": "christianity.orthodox.canonical.antiochian",
    "410": "christianity.orthodox.canonical.serbian",
    "401": "christianity.orthodox.canonical.rocor",
    "022": "christianity.orthodox.canonical.carpatho-russian",
    "395": "christianity.orthodox.canonical.romanian",
    "078": "christianity.orthodox.canonical.bulgarian",
    "431": "christianity.orthodox.canonical.ukrainian",
    "330": "christianity.orthodox.canonical.macedonian",
    "242": "christianity.orthodox.canonical.georgian",
    "009": "christianity.orthodox.canonical.albanian",
    "400": "christianity.orthodox.canonical.patriarchal-parishes",
    "FFK": "christianity.orthodox.oldcalendarist.goc",
    "251": "christianity.orthodox.oldcalendarist.hocna",
    "FFV": "christianity.orthodox.other.belarusan",
    "F52": "christianity.orthodox.other.syro-russian",

    # ---------------------------------------------------------------- Oriental Orthodox
    "186": "christianity.oriental.coptic",
    "204": "christianity.oriental.ethiopian",
    "202": "christianity.oriental.eritrean",
    "050": "christianity.oriental.armenian-etchmiadzin",
    "049": "christianity.oriental.armenian-cilicia",
    "423": "christianity.oriental.syriac",
    "333": "christianity.oriental.malankara-orthodox",
    "334": "christianity.oriental.malankara-syriac",
    "F28": "christianity.oriental.marthoma",
    "FFL": "christianity.oriental.knanaya",

    # ---------------------------------------------------------------- Anglican
    "193": "christianity.anglican.episcopal",
    "033": "christianity.anglican.acna",
    "375": "christianity.anglican.continuing.rec",
    "F01": "christianity.anglican.continuing.acc",
    "FG4": "christianity.anglican.continuing.aca",
    "FG3": "christianity.anglican.continuing.apa",
    "FG2": "christianity.anglican.continuing.apck",
    "FG6": "christianity.anglican.continuing.american-anglican",
    "FGA": "christianity.anglican.continuing.oac",
    "FG5": "christianity.anglican.continuing.uecna",
    "FG8": "christianity.anglican.continuing.emc",
    "FG7": "christianity.anglican.continuing.holy-cross",
    "FG9": "christianity.anglican.continuing.hccar",
    "FE9": "christianity.anglican.continuing.cec",

    # ---------------------------------------------------------------- Lutheran
    "207": "christianity.lutheran.elca",
    "283": "christianity.lutheran.lcms",
    "469": "christianity.lutheran.wels",
    "209": "christianity.lutheran.els",
    "314": "christianity.lutheran.nalc",
    "255": "christianity.lutheran.lcmc",
    "220": "christianity.lutheran.aflc",
    "284": "christianity.lutheran.aalc",
    "163": "christianity.lutheran.clb",
    "164": "christianity.lutheran.clc",
    "045": "christianity.lutheran.apostolic",
    "FFH": "christianity.lutheran.old-apostolic",
    "FFJ": "christianity.lutheran.laestadian",
    "274": "christianity.lutheran.latvian",
    "FFG": "christianity.lutheran.concordia",
    "FFF": "christianity.lutheran.elcm",
    "FFE": "christianity.lutheran.eldona",
    "FFD": "christianity.lutheran.independent-diocese",
    "FFC": "christianity.lutheran.olcc",

    # ---------------------------------------------------------------- Presbyterian
    "355": "christianity.reformed.presbyterian.pcusa",
    "356": "christianity.reformed.presbyterian.pca",
    "216": "christianity.reformed.presbyterian.epc",
    "335": "christianity.reformed.presbyterian.opc",
    "055": "christianity.reformed.presbyterian.arp",
    "185": "christianity.reformed.presbyterian.cumberland",
    "187": "christianity.reformed.presbyterian.cumberland-america",
    "383": "christianity.reformed.presbyterian.rpcna",
    "069": "christianity.reformed.presbyterian.bpc",
    "FFW": "christianity.reformed.presbyterian.eco",
    "FF6": "christianity.reformed.presbyterian.covenant",
    "184": "christianity.reformed.presbyterian.covenant-reformed",
    "354": "christianity.reformed.presbyterian.prc",
    "380": "christianity.reformed.presbyterian.rpcga",
    "382": "christianity.reformed.presbyterian.hanover",
    "FFQ": "christianity.reformed.presbyterian.vanguard",
    "FJ5": "christianity.reformed.presbyterian.wepc",
    "FJ6": "christianity.reformed.presbyterian.evangel",
    "030": "christianity.reformed.presbyterian.american",
    "222": "christianity.reformed.presbyterian.fpcna",
    "FFA": "christianity.reformed.presbyterian.fpcs",
    "224": "christianity.reformed.presbyterian.fcsc",

    # ---------------------------------------------------------------- Continental Reformed
    "371": "christianity.reformed.continental.rca",
    "105": "christianity.reformed.continental.crcna",
    "455": "christianity.reformed.continental.urcna",
    "369": "christianity.reformed.continental.prca",
    "307": "christianity.reformed.continental.nrc",
    "227": "christianity.reformed.continental.frcna",
    "248": "christianity.reformed.continental.heritage",
    "086": "christianity.reformed.continental.canrc",
    "373": "christianity.reformed.continental.rcus",
    "210": "christianity.reformed.continental.federation",
    "172": "christianity.reformed.continental.crec",
    "FGB": "christianity.reformed.continental.reformed-bible",
    "FFB": "christianity.reformed.continental.rcna",

    # ---------------------------------------------------------------- Congregational
    "443": "christianity.reformed.congregational.ucc",
    "175": "christianity.reformed.congregational.naccc",
    "181": "christianity.reformed.congregational.cccc",
    "176": "christianity.reformed.congregational.additional",
    "198": "christianity.reformed.congregational.earccc",
    "F32": "christianity.reformed.congregational.north-carolina",
    "F26": "christianity.reformed.congregational.kentucky",
    "F49": "christianity.reformed.congregational.southern-illinois",
    "051": "christianity.reformed.congregational.armenian-evangelical",

    # ---------------------------------------------------------------- Baptist
    "419": "christianity.baptist.sbc",
    "019": "christianity.baptist.abcusa",
    "300": "christianity.baptist.national.nbcusa",
    "301": "christianity.baptist.national.nbca",
    "302": "christianity.baptist.national.nmbc",
    "364": "christianity.baptist.national.pnbc",
    "223": "christianity.baptist.freewill.nafwb",
    "336": "christianity.baptist.freewill.original",
    "F57": "christianity.baptist.freewill.uafwb",
    "347": "christianity.baptist.freewill.pentecostal",
    "361": "christianity.baptist.primitive.associations",
    "304": "christianity.baptist.primitive.npbc",
    "362": "christianity.baptist.primitive.eastern-district",
    "365": "christianity.baptist.primitive.progressive",
    "FFX": "christianity.baptist.oldregular.indian-bottom",
    "FFY": "christianity.baptist.oldregular.northern-new-salem",
    "FFZ": "christianity.baptist.oldregular.sardis",
    "FG1": "christianity.baptist.oldregular.solid-rock",
    "017": "christianity.baptist.landmark.aba",
    "059": "christianity.baptist.landmark.bmaa",
    "082": "christianity.baptist.landmark.central",
    "388": "christianity.baptist.independent.garbc",
    "308": "christianity.baptist.independent.ntaibc",
    "047": "christianity.baptist.reformed.arbca",
    "F41": "christianity.baptist.reformed.rbnet",
    "F51": "christianity.baptist.reformed.sovereign-grace",
    "057": "christianity.baptist.converge",
    "313": "christianity.baptist.nabc",
    "179": "christianity.baptist.venture",
    "231": "christianity.baptist.general",
    "415": "christianity.baptist.seventhday",
    "012": "christianity.baptist.alliance",

    # ---------------------------------------------------------------- Methodist
    "449": "christianity.methodist.umc",
    "221": "christianity.methodist.free",
    "363": "christianity.methodist.primitive",
    "003": "christianity.methodist.african.ame",
    "005": "christianity.methodist.african.amez",
    "101": "christianity.methodist.african.cme",
    "FGV": "christianity.methodist.african.uame",
    "384": "christianity.methodist.african.rzua",
    "421": "christianity.methodist.holiness.southern",
    "180": "christianity.methodist.holiness.congregational-methodist",
    "215": "christianity.methodist.holiness.evangelical-methodist",
    "FE8": "christianity.methodist.holiness.bible-methodist",
    "279": "christianity.methodist.holiness.lumber-river",
    "197": "christianity.methodist.holiness.evangelical-church",
    "438": "christianity.methodist.unitedbrethren.ub",
    "199": "christianity.methodist.unitedbrethren.ecc",

    # ---------------------------------------------------------------- Holiness
    "165": "christianity.holiness.nazarene",
    "123": "christianity.holiness.cog-anderson",
    "089": "christianity.holiness.cma",
    "403": "christianity.holiness.salvation-army",
    "168": "christianity.holiness.cccu",
    "171": "christianity.holiness.cogc-winebrenner",
    "217": "christianity.holiness.bible-holiness",
    "247": "christianity.holiness.hcog",
    "110": "christianity.holiness.coch",
    "D83": "christianity.holiness.cshc",
    "467": "christianity.holiness.wesleyan",

    # ---------------------------------------------------------------- Pentecostal
    "053": "christianity.pentecostal.trinitarian.assemblies-of-god",
    "127": "christianity.pentecostal.trinitarian.cog-cleveland",
    "145": "christianity.pentecostal.trinitarian.cogop",
    "141": "christianity.pentecostal.trinitarian.cogic",
    "263": "christianity.pentecostal.trinitarian.foursquare",
    "329": "christianity.pentecostal.trinitarian.open-bible",
    "339": "christianity.pentecostal.trinitarian.pcg",
    "190": "christianity.pentecostal.trinitarian.elim",
    "265": "christianity.pentecostal.trinitarian.ipcc",
    "146": "christianity.pentecostal.trinitarian.cogma",
    "120": "christianity.pentecostal.trinitarian.cogaf",
    "346": "christianity.pentecostal.trinitarian.fbhca",
    "177": "christianity.pentecostal.trinitarian.congregational-holiness",
    "FFR": "christianity.pentecostal.trinitarian.fgcai",
    "FGL": "christianity.pentecostal.trinitarian.fca",
    "260": "christianity.pentecostal.trinitarian.ifca-assemblies",
    "F23": "christianity.pentecostal.trinitarian.fgai",
    "042": "christianity.pentecostal.trinitarian.afm-portland",
    "F10": "christianity.pentecostal.trinitarian.ccna",
    "445": "christianity.pentecostal.trinitarian.uhca",
    "122": "christianity.pentecostal.trinitarian.cogbf",
    "A47": "christianity.pentecostal.trinitarian.colg-cwff",
    "D59": "christianity.pentecostal.trinitarian.colg-pillar",
    "D92": "christianity.pentecostal.trinitarian.house-of-god",
    "F58": "christianity.pentecostal.trinitarian.house-of-prayer",
    "232": "christianity.pentecostal.trinitarian.fgbcf",
    "326": "christianity.pentecostal.trinitarian.original-cog",
    "F53": "christianity.pentecostal.trinitarian.cog-unspecified",
    "454": "christianity.pentecostal.oneness.upci",
    "D71": "christianity.pentecostal.oneness.paw",
    "155": "christianity.pentecostal.oneness.cooljc",
    "E54": "christianity.pentecostal.oneness.bibleway",
    "FGJ": "christianity.pentecostal.oneness.aljc",
    "125": "christianity.pentecostal.oneness.cog-apostolic",
    "065": "christianity.pentecostal.oneness.bethel",
    "FGD": "christianity.pentecostal.oneness.higher-ground",
    "F16": "christianity.pentecostal.oneness.firstborn",
    "463": "christianity.pentecostal.charismatic.vineyard",
    "084": "christianity.pentecostal.charismatic.calvary-chapel",
    "FGP": "christianity.pentecostal.charismatic.every-nation",
    "350": "christianity.pentecostal.charismatic.pillar",

    # ---------------------------------------------------------------- Restorationist
    "167": "christianity.restorationist.churches-of-christ",
    "097": "christianity.restorationist.christian-churches",
    "093": "christianity.restorationist.disciples",
    "264": "christianity.restorationist.icoc",
    "F13": "christianity.restorationist.church-of-christ-unspecified",

    # ---------------------------------------------------------------- Adventist
    "413": "christianity.adventist.sda",
    "001": "christianity.adventist.advent-christian",
    "133": "christianity.adventist.cog7",
    "121": "christianity.adventist.coggc",
    "FGN": "christianity.adventist.ucg",
    "FGM": "christianity.adventist.gci",

    # ---------------------------------------------------------------- Latter Day Saints
    "151": "christianity.latterday.lds",
    "173": "christianity.latterday.community-of-christ",
    "149": "christianity.latterday.bickertonite",

    # ---------------------------------------------------------------- Anabaptist: Amish
    "031": "christianity.anabaptist.amish.undifferentiated",
    "061": "christianity.anabaptist.amish.beachy",
    "424": "christianity.anabaptist.amish.tampico",
    "278": "christianity.anabaptist.amish.maranatha",
    "016": "christianity.anabaptist.amish.ambassadors",
    "062": "christianity.anabaptist.amish.berea",
    "310": "christianity.anabaptist.amish.midwest-beachy",
    "432": "christianity.anabaptist.amish.unaffiliated-conservative",
    "FHH": "christianity.anabaptist.amish.spring-garden",

    # ---------------------------------------------------------------- Anabaptist: Mennonite
    "288": "christianity.anabaptist.mennonite.mcusa",
    "237": "christianity.anabaptist.mennonite.usmb",
    "183": "christianity.anabaptist.mennonite.cmc",
    "143": "christianity.anabaptist.mennonite.holdeman",
    "FJ3": "christianity.anabaptist.mennonite.weaverland",
    "286": "christianity.anabaptist.mennonite.eastern-pa",
    "414": "christianity.anabaptist.mennonite.stauffer",
    "FHV": "christianity.anabaptist.mennonite.stauffer-independent",
    "FDZ": "christianity.anabaptist.mennonite.mid-atlantic",
    "F38": "christianity.anabaptist.mennonite.pilgrim",
    "FD7": "christianity.anabaptist.mennonite.washington-franklin",
    "F27": "christianity.anabaptist.mennonite.keystone",
    "282": "christianity.anabaptist.mennonite.mcf",
    "FHF": "christianity.anabaptist.mennonite.unaffiliated-conservative",
    "F31": "christianity.anabaptist.mennonite.nationwide",
    "FHW": "christianity.anabaptist.mennonite.bma",
    "FD1": "christianity.anabaptist.mennonite.midwest",
    "FE1": "christianity.anabaptist.mennonite.wisler-oh-in",
    "FD9": "christianity.anabaptist.mennonite.wisler-oh",
    "FHR": "christianity.anabaptist.mennonite.wisler-fellowship",
    "FHQ": "christianity.anabaptist.mennonite.hoover",
    "FDT": "christianity.anabaptist.mennonite.bethel",
    "F48": "christianity.anabaptist.mennonite.southeastern",
    "FE2": "christianity.anabaptist.mennonite.hope",
    "FD8": "christianity.anabaptist.mennonite.western-conservative",
    "FFU": "christianity.anabaptist.mennonite.meadow-springs",
    "FD2": "christianity.anabaptist.mennonite.northeastern",
    "FHM": "christianity.anabaptist.mennonite.reidenbach",
    "FDW": "christianity.anabaptist.mennonite.cumberland-valley",
    "FF5": "christianity.anabaptist.mennonite.riverdale",
    "FD6": "christianity.anabaptist.mennonite.grandview",
    "FDY": "christianity.anabaptist.mennonite.little-flock",
    "FF3": "christianity.anabaptist.mennonite.original-virginia",
    "FD5": "christianity.anabaptist.mennonite.south-atlantic",
    "FDX": "christianity.anabaptist.mennonite.haven",
    "FDV": "christianity.anabaptist.mennonite.york-adams",
    "FHU": "christianity.anabaptist.mennonite.orthodox",
    "FEY": "christianity.anabaptist.mennonite.appalachian",
    "FF4": "christianity.anabaptist.mennonite.pleasant-view",
    "FD4": "christianity.anabaptist.mennonite.old-wenger",
    "379": "christianity.anabaptist.mennonite.reformed",
    "291": "christianity.anabaptist.mennonite.missionary-church",
    "073": "christianity.anabaptist.mennonite.bible-fellowship",
    "213": "christianity.anabaptist.mennonite.fec",
    "211": "christianity.anabaptist.mennonite.febc",
    "FHG": "christianity.anabaptist.mennonite.remnant",
    "FHJ": "christianity.anabaptist.mennonite.agape",
    "FFS": "christianity.anabaptist.mennonite.adc",
    "FEZ": "christianity.anabaptist.mennonite.believers-in-christ",
    "FF1": "christianity.anabaptist.mennonite.christian-communities",

    # ---------------------------------------------------------------- Anabaptist: Hutterite
    "FJ1": "christianity.anabaptist.hutterite.schmiedeleut-1",
    "FJ2": "christianity.anabaptist.hutterite.schmiedeleut-2",
    "FHZ": "christianity.anabaptist.hutterite.lehrerleut",
    "FHX": "christianity.anabaptist.hutterite.dariusleut",
    "FHY": "christianity.anabaptist.hutterite.christian-communities",
    "070": "christianity.anabaptist.hutterite.bruderhof",

    # ---------------------------------------------------------------- Anabaptist: Brethren
    "157": "christianity.anabaptist.brethren.cob",
    "075": "christianity.anabaptist.brethren.bic",
    "071": "christianity.anabaptist.brethren.ashland",
    "244": "christianity.anabaptist.brethren.charis",
    "FF2": "christianity.anabaptist.brethren.ogbb",
    "F35": "christianity.anabaptist.brethren.ogbb-new",
    "FFT": "christianity.anabaptist.brethren.dunkard",
    "324": "christianity.anabaptist.brethren.river",
    "459": "christianity.anabaptist.brethren.united-zion",
    "C51": "christianity.anabaptist.brethren.old-order-german-baptist",
    "FJ4": "christianity.anabaptist.brethren.german-baptist",
    "FD3": "christianity.anabaptist.brethren.old-brethren-german-baptist",
    "FHT": "christianity.anabaptist.brethren.old-brethren-goshen",
    "FHS": "christianity.anabaptist.brethren.old-brethren-california",
    "FHK": "christianity.anabaptist.brethren.independent-conservative",

    # ---------------------------------------------------------------- Anabaptist: Apostolic
    "040": "christianity.anabaptist.apostolic.acca",
    "FEX": "christianity.anabaptist.apostolic.faith",
    "FF7": "christianity.anabaptist.apostolic.nazarean-east",
    "FF8": "christianity.anabaptist.apostolic.nazarean-west",
    "FHN": "christianity.anabaptist.apostolic.german",
    "FDU": "christianity.anabaptist.apostolic.christian-apostolic",
    "FHP": "christianity.anabaptist.apostolic.nazarene-christian",

    # ---------------------------------------------------------------- Friends
    "391": "christianity.friends.fgc",
    "225": "christianity.friends.fum",
    "328": "christianity.friends.efci",
    "393": "christianity.friends.dually-aligned",
    "390": "christianity.friends.conservative-ym",
    "338": "christianity.friends.independent-ym",
    "389": "christianity.friends.unaffiliated",

    # ---------------------------------------------------------------- Moravian, Plymouth, Pietist
    "293": "christianity.moravian.northern",
    "295": "christianity.moravian.southern",
    "292": "christianity.moravian.alaska",
    "461": "christianity.moravian.unity-of-the-brethren",
    "353": "christianity.plymouth.open",
    "201": "christianity.pietist.covenant",
    "203": "christianity.pietist.efca",

    # ---------------------------------------------------------------- Non-denominational
    "500": "christianity.nondenominational.independent",
    "262": "christianity.nondenominational.iccc",
    "256": "christianity.nondenominational.ifbc",
    "063": "christianity.nondenominational.berean",
    "243": "christianity.nondenominational.grace-gospel",
    "067": "christianity.nondenominational.ffbc",

    # ---------------------------------------------------------------- standalone Christian
    "272": "christianity.witnesses",
    "111": "christianity.christianscience",
    "239": "christianity.swedenborgian.swedenborgian-church",
    "233": "christianity.swedenborgian.general-church",
    "437": "christianity.messianic.umjc",
    "058": "christianity.messianic.amc",
    "087": "christianity.other.christadelphian",
    "309": "christianity.other.new-apostolic",
    "290": "christianity.other.mcc",
    "015": "christianity.other.amana",
    "405": "christianity.other.schwenkfelder",
    "FGQ": "christianity.other.twelve-tribes",
    "F54": "christianity.other.local-churches",

    # ---------------------------------------------------------------- other families
    "276": "judaism.orthodox",
    "FGS": "judaism.chabad",
    "270": "judaism.conservative",
    "271": "judaism.reform",
    "275": "judaism.reconstructionist",
    "FGR": "judaism.independent",
    "267": "islam",
    "895": "hinduism.temples",
    "462": "hinduism.vedanta",
    "890": "buddhism.mahayana",
    "891": "buddhism.theravada",
    "892": "buddhism.vajrayana",
    "416": "sikhism",
    "268": "jainism",
    "490": "zoroastrianism",
    "056": "bahai",
    "408": "shinto",
    "425": "daoism",
    "FER": "unification",
    "124": "newthought.unity",
    "303": "spiritualism.nsac",
    "435": "unitarianuniversalist",
    "C22": "hebrewisraelite.cogasoc",
    "904": "secular.ethicalculture",
}
