"""Australia, Census 2021, language used at home (ASCL 2016 labels) -> node.

Keys are the ABS's own labels as sources/au_census.py writes them: four-digit ASCL languages
(Table 5 and QuickStats), G13's named languages (the same labels), "English only", and G13's
five remainders, which countries/au.py shares out over their four-digit members and only falls
back to the group node below when a state publishes no member at all.

Calls worth knowing (sources/au.md says more):
  * Australian Indigenous languages sit under the areal root `australian` (tree.d/au.txt says
    why). "X, nfd" and "X, nec" go on the narrowest node holding all of X: "Arrernte, nfd"
    (1,437) on the Arrernte group, as Canada's "Cree, n.o.s." sits on Cree; "Yolngu Matha, nfd"
    on Yolngu Matha; "Cape York Peninsula Languages, nec" (2,701) on Pama-Nyungan, since the
    ABS's Cape York group is geographic and all its languages are Pama-Nyungan; "Kimberley Area
    Languages, nec", "Australian Indigenous Languages, nfd" and "Other Australian Indigenous
    Languages, nec" on the root. "Djinang, nfd" and "Djinang, nec" both go on Djinang: Djinang
    is one language and the codes are its unnamed varieties.
  * "Karen" (13,181) is a named answer but names a group (S'gaw, Pwo, Karenni...), so it sits on
    the Karen group, as ca2021's "Karen, n.o.s." does.
  * "Burmese and Related Languages, nec/nfd" on Sino-Tibetan: the ABS group holds Rohingya, but
    Rohingya has its own code, and Shan and Mon have theirs under Tai and Mon-Khmer, so what is
    left is Myanmar's Tibeto-Burman languages (Kachin, the other Chin languages, Kayah...).
  * Regional remainders that cross families go on `other`: "Southern Asian Languages, nfd",
    "Other Southern Asian Languages" (the ABS's residual after Indo-Aryan and Dravidian),
    "African Languages, nfd/nec", "Eastern European Languages, nfd", "Papua New Guinea
    Languages, nfd/nec", "Timorese" (Tetum, Mambai, Fataluku...), "Cypriot, so described"
    (Greek or Turkish), "Invented Languages". "Swiss, so described" goes on Indo-European.
  * "Ndebele" on Zimbabwean Ndebele: Australia's Ndebele speakers came with its Shona speakers
    (13,785), not from South Africa, whose Nguni languages are tiny here (Zulu 652, Xhosa 152).
  * "Ewe" on Gbe (us.txt's node is "Gbe (Ewe, Fon)"). "Bisaya" on Bisayan. "Ilonggo" on
    Hiligaynon. "Pampangan" on Kapampangan. "Oriya" on Odia. "Sinhalese" on Sinhala.
    "Serbo-Croatian/Yugoslavian, so described" on Serbo-Croatian. "Czechoslovakian, so
    described" on West Slavic. "Romany" on Romani.
  * "Inadequately described" (18,150) and "Non-verbal, so described" (24,625) name no language:
    not drawn, in `gap` with "Not stated".
"""
IE = "indoeuropean"
GE = f"{IE}.germanic"
RO = f"{IE}.romance"
SL = f"{IE}.slavic"
IA = f"{IE}.indoaryan"
IR = f"{IE}.iranian"
AA = "afroasiatic"
AN = "austronesian"
OC = f"{AN}.oceanic"
PH = f"{AN}.philippine"
NC = "nigercongo"
NS = "nilosaharan"
ST = "sinotibetan"
CR = "creole"
AU = "australian"
PN = f"{AU}.pamanyungan"
WD = f"{PN}.westerndesert"
AR = f"{PN}.arandic"
NY = f"{PN}.ngumpinyapa"
YO = f"{PN}.yolngu"
SW = f"{PN}.southwest"
SE = f"{PN}.southeast"

NAMES = {
    # ---- G13 ----
    "English only": f"{GE}.english",
    "Other Chinese languages": f"{ST}.sinitic",
    "Other Indo-Aryan languages": IA,
    "Other Southeast Asian Austronesian languages": AN,
    "Australian Indigenous languages": AU,
    "Other languages": "other",
    # ---- Northern European ----
    "Afrikaans": f"{GE}.continental.afrikaans",
    "Celtic, nec": f"{IE}.celtic",
    "Celtic, nfd": f"{IE}.celtic",
    "Danish": f"{GE}.north.danish",
    "Dutch": f"{GE}.continental.dutch",
    "English": f"{GE}.english",
    "Estonian": "uralic.estonian",
    "Finnish": "uralic.finnish",
    "Frisian": f"{GE}.frisian",
    "Gaelic (Scotland)": f"{IE}.celtic.scottishgaelic",
    "German": f"{GE}.continental.german",
    "Icelandic": f"{GE}.north.icelandic",
    "Irish": f"{IE}.celtic.irish",
    "Letzeburgish": f"{GE}.continental.luxembourgish",
    "Norwegian": f"{GE}.north.norwegian",
    "Scandinavian, nec": f"{GE}.north",
    "Scandinavian, nfd": f"{GE}.north",
    "Swedish": f"{GE}.north.swedish",
    "Welsh": f"{IE}.celtic.welsh",
    "Yiddish": f"{GE}.continental.yiddish",
    # ---- Southern European ----
    "Basque": "isolate.basque",
    "Catalan": f"{RO}.catalan",
    "French": f"{RO}.french",
    "Greek": f"{IE}.hellenic.greek",
    "Iberian Romance, nec": RO,
    "Iberian Romance, nfd": RO,
    "Italian": f"{RO}.italian",
    "Latin": f"{RO}.latin",
    "Maltese": f"{AA}.maltese",
    "Other Southern European Languages, nec": "other",   # Basque and Latin's group
    "Portuguese": f"{RO}.portuguese",
    "Spanish": f"{RO}.spanish",
    # ---- Eastern European ----
    "Albanian": f"{IE}.albanian.albanian",
    "Aromunian (Macedo-Romanian)": f"{RO}.aromanian",
    "Belorussian": f"{SL}.east.belarusian",
    "Bosnian": f"{SL}.south.bosnian",
    "Bulgarian": f"{SL}.south.bulgarian",
    "Croatian": f"{SL}.south.croatian",
    "Czech": f"{SL}.west.czech",
    "Czechoslovakian, so described": f"{SL}.west",
    "East Slavic, nfd": f"{SL}.east",
    "Eastern European Languages, nfd": "other",          # includes Hungarian, Albanian
    "Hungarian": "uralic.hungarian",
    "Latvian": f"{IE}.baltic.latvian",
    "Lithuanian": f"{IE}.baltic.lithuanian",
    "Macedonian": f"{SL}.south.macedonian",
    "Other Eastern European Languages, nec": IE,         # Albanian, Romanian, Romany's group
    "Polish": f"{SL}.west.polish",
    "Romanian": f"{RO}.romanian",
    "Romany": f"{IA}.romani.romani",
    "Russian": f"{SL}.east.russian",
    "Serbian": f"{SL}.south.serbian",
    "Serbo-Croatian/Yugoslavian, so described": f"{SL}.south.serbocroatian",
    "Slovak": f"{SL}.west.slovak",
    "Slovene": f"{SL}.south.slovenian",
    "South Slavic, nfd": f"{SL}.south",
    "Ukrainian": f"{SL}.east.ukrainian",
    # ---- Southwest and Central Asian ----
    "Arabic": f"{AA}.arabic",
    "Armenian": f"{IE}.armenian.armenian",
    "Assyrian Neo-Aramaic": f"{AA}.assyrian",
    "Azeri": "turkic.azerbaijani",
    "Balochi": f"{IR}.balochi",
    "Chaldean Neo-Aramaic": f"{AA}.chaldean",
    "Dari": f"{IR}.dari",
    "Georgian": "kartvelian.georgian",
    "Hazaraghi": f"{IR}.hazaragi",
    "Hebrew": f"{AA}.hebrew",
    "Iranic, nec": IR,
    "Iranic, nfd": IR,
    "Kurdish": f"{IR}.kurdish",
    "Mandaean (Mandaic)": f"{AA}.mandaic",
    "Middle Eastern Semitic Languages, nec": AA,
    "Middle Eastern Semitic Languages, nfd": AA,
    "Other Southwest and Central Asian Languages, nec": "other",
    "Pashto": f"{IR}.pashto",
    "Persian (excluding Dari)": f"{IR}.persian",
    "Tatar": "turkic.tatar",
    "Turkic, nec": "turkic",
    "Turkic, nfd": "turkic",
    "Turkish": "turkic.turkish",
    "Turkmen": "turkic.turkmen",
    "Uygur": "turkic.uyghur",
    "Uzbek": "turkic.uzbek",
    # ---- Southern Asian ----
    "Assamese": f"{IA}.eastern.assamese",
    "Bengali": f"{IA}.eastern.bengali",
    "Dhivehi": f"{IA}.dhivehi",
    "Dravidian, nec": "dravidian",
    "Fijian Hindustani": f"{IA}.eastcentral.fiji_hindi",
    "Gujarati": f"{IA}.gujarati.gujarati",
    "Hindi": f"{IA}.central.hindi",
    "Indo-Aryan, nec": IA,
    "Indo-Aryan, nfd": IA,
    "Kannada": "dravidian.southern.kannada",
    "Kashmiri": f"{IA}.dardic.kashmiri",
    "Konkani": f"{IA}.southern.konkani",
    "Malayalam": "dravidian.southern.malayalam",
    "Marathi": f"{IA}.southern.marathi",
    "Nepali": f"{IA}.pahari.eastern.nepali",
    "Oriya": f"{IA}.eastern.odia",
    "Other Southern Asian Languages": "other",
    "Punjabi": f"{IA}.northwestern.punjabi",
    "Sindhi": f"{IA}.northwestern.sindhi",
    "Sinhalese": f"{IA}.sinhala",
    "Southern Asian Languages, nfd": "other",
    "Tamil": "dravidian.southern.tamil",
    "Telugu": "dravidian.southcentral.telugu",
    "Tulu": "dravidian.southern.tulu",
    "Urdu": f"{IA}.central.urdu",
    # ---- Southeast Asian ----
    "Acehnese": f"{AN}.acehnese",
    "Balinese": f"{AN}.balinese",
    "Bikol": f"{PH}.bikol",
    "Bisaya": f"{PH}.bisayan",
    "Burmese": f"{ST}.burmish.burmese",
    "Burmese and Related Languages, nec": ST,
    "Burmese and Related Languages, nfd": ST,
    "Cebuano": f"{PH}.cebuano",
    "Chin Haka": f"{ST}.kukichin.hakha",
    "Filipino": f"{PH}.filipino",
    "Hmong": "hmongmien.hmong",
    "Iban": f"{AN}.malayic.iban",
    "Ilokano": f"{PH}.ilocano",
    "Ilonggo (Hiligaynon)": f"{PH}.hiligaynon",
    "Indonesian": f"{AN}.malayic.indonesian",
    "Javanese": f"{AN}.javanese",
    "Karen": f"{ST}.karen",
    "Khmer": "austroasiatic.khmer",
    "Lao": "kradai.lao",
    "Malay": f"{AN}.malayic.malay",
    "Mon": "austroasiatic.mon",
    "Mon-Khmer, nec": "austroasiatic",
    "Mon-Khmer, nfd": "austroasiatic",
    "Other Southeast Asian Languages": "other",
    "Pampangan": f"{PH}.kapampangan",
    "Rohingya": f"{IA}.eastern.rohingya",
    "Southeast Asian Austronesian Languages, nec": AN,
    "Southeast Asian Austronesian Languages, nfd": AN,
    "Southeast Asian Languages, nfd": "other",
    "Tagalog": f"{PH}.tagalog",
    "Tai, nec": "kradai",
    "Tai, nfd": "kradai",
    "Tetum": f"{AN}.tetun",
    "Thai": "kradai.thai",
    "Timorese": "other",
    "Vietnamese": "austroasiatic.vietnamese",
    "Zomi": f"{ST}.kukichin.zomi",
    # ---- Eastern Asian ----
    "Cantonese": f"{ST}.sinitic.cantonese",
    "Chinese, nec": f"{ST}.sinitic",
    "Chinese, nfd": f"{ST}.sinitic",
    "Eastern Asian Languages, nfd": "other",
    "Hakka": f"{ST}.sinitic.hakka",
    "Japanese": "japonic.japanese",
    "Korean": "koreanic.korean",
    "Mandarin": f"{ST}.sinitic.mandarin",
    "Min Nan": f"{ST}.sinitic.min_nan",
    "Mongolian": "mongolic.mongolian",
    "Other Eastern Asian Languages, nec": "other",
    "Tibetan": f"{ST}.tibetic.tibetan",
    "Wu": f"{ST}.sinitic.wu",
    # ---- Australian Indigenous ----
    "Aboriginal English, so described": f"{AU}.contact.aboriginal_english",
    "Kriol": f"{AU}.contact.kriol",
    "Yumplatok (Torres Strait Creole)": f"{AU}.contact.yumplatok",
    "Gurindji Kriol": f"{AU}.contact.gurindji_kriol",
    "Australian Indigenous Languages, nfd": AU,
    "Other Australian Indigenous Languages, nec": AU,
    "Other Australian Indigenous Languages, nfd": AU,
    "Arnhem Land and Daly River Region Languages, nec": AU,
    "Arnhem Land and Daly River Region Languages, nfd": AU,
    "Kimberley Area Languages, nec": AU,
    "Kimberley Area Languages, nfd": AU,
    "Torres Strait Island Languages, nfd": AU,
    "Northern Desert Fringe Area Languages, nec": PN,
    "Northern Desert Fringe Area Languages, nfd": PN,
    "Cape York Peninsula Languages, nec": PN,
    "Cape York Peninsula Languages, nfd": PN,
    "Kalaw Kawaw Ya/Kalaw Lagaw Ya": f"{PN}.kalaw_lagaw_ya",
    "Meriam Mir": f"{AU}.meriam",
    # Western Desert
    "Western Desert Languages, nec": WD,
    "Western Desert Languages, nfd": WD,
    "Pitjantjatjara": f"{WD}.pitjantjatjara",
    "Yankunytjatjara": f"{WD}.yankunytjatjara",
    "Ngaanyatjarra": f"{WD}.ngaanyatjarra",
    "Luritja": f"{WD}.luritja",
    "Pintupi": f"{WD}.pintupi",
    "Martu Wangka": f"{WD}.martu_wangka",
    "Manyjilyjarra": f"{WD}.manyjilyjarra",
    "Kukatja": f"{WD}.kukatja",
    "Wangkatha": f"{WD}.wangkatha",
    "Kukatha": f"{WD}.kukatha",
    "Antikarinya": f"{WD}.antikarinya",
    "Wangkajunga": f"{WD}.wangkajunga",
    "Yulparija": f"{WD}.yulparija",
    "Tjupany": f"{WD}.tjupany",
    "Warnman": f"{WD}.warnman",
    # Arandic
    "Arandic, nec": AR,
    "Arandic, nfd": AR,
    "Arrernte, nec": f"{AR}.arrernte",
    "Arrernte, nfd": f"{AR}.arrernte",
    "Eastern Arrernte": f"{AR}.arrernte.eastern",
    "Western Arrarnta": f"{AR}.arrernte.western",
    "Anmatyerr, nec": f"{AR}.anmatyerr",
    "Anmatyerr, nfd": f"{AR}.anmatyerr",
    "Central Anmatyerr": f"{AR}.anmatyerr.central",
    "Eastern Anmatyerr": f"{AR}.anmatyerr.eastern",
    "Alyawarr": f"{AR}.alyawarr",
    "Kaytetye": f"{AR}.kaytetye",
    # Ngumpin-Yapa (the ABS's Northern Desert Fringe group, less Warumungu and the mixed
    # languages)
    "Warlpiri": f"{NY}.warlpiri",
    "Gurindji": f"{NY}.gurindji",
    "Jaru": f"{NY}.jaru",
    "Walmajarri": f"{NY}.walmajarri",
    "Ngarinyman": f"{NY}.ngarinyman",
    "Mudburra": f"{NY}.mudburra",
    "Bilinarra": f"{NY}.bilinarra",
    "Malngin": f"{NY}.malngin",
    "Wanyjirra": f"{NY}.wanyjirra",
    "Warlmanpa": f"{NY}.warlmanpa",
    # Yolngu Matha
    "Yolngu Matha, nfd": YO,
    "Other Yolngu Matha, nec": YO,
    "Dhangu, nec": YO,
    "Dhangu, nfd": YO,
    "Dhay'yi, nec": YO,
    "Dhay'yi, nfd": YO,
    "Dhuwal, nec": YO,
    "Dhuwal, nfd": YO,
    "Dhuwala, nec": YO,
    "Dhuwala, nfd": YO,
    "Djinba, nec": YO,
    "Djinba, nfd": YO,
    "Yakuy, nec": YO,
    "Yakuy, nfd": YO,
    "Nhangu, nec": f"{YO}.nhangu",
    "Nhangu": f"{YO}.nhangu",
    "Djinang, nec": f"{YO}.djinang",
    "Djinang, nfd": f"{YO}.djinang",
    "Djambarrpuyngu": f"{YO}.djambarrpuyngu",
    "Gupapuyngu": f"{YO}.gupapuyngu",
    "Gumatj": f"{YO}.gumatj",
    "Dhuwaya": f"{YO}.dhuwaya",
    "Galpu": f"{YO}.galpu",
    "Wurlaki": f"{YO}.wurlaki",
    "Djapu": f"{YO}.djapu",
    "Daatiwuy": f"{YO}.daatiwuy",
    "Liyagalawumirr": f"{YO}.liyagalawumirr",
    "Golumala": f"{YO}.golumala",
    "Wangurri": f"{YO}.wangurri",
    "Dhalwangu": f"{YO}.dhalwangu",
    "Ritharrngu": f"{YO}.ritharrngu",
    "Wagilak": f"{YO}.wagilak",
    "Warramiri": f"{YO}.warramiri",
    "Rirratjingu": f"{YO}.rirratjingu",
    "Madarrpa": f"{YO}.madarrpa",
    "Ganalbingu": f"{YO}.ganalbingu",
    "Djinba": f"{YO}.djinba",
    # South-West
    "Nyungar": f"{SW}.nyungar",
    "Wajarri": f"{SW}.wajarri",
    "Yindjibarndi": f"{SW}.yindjibarndi",
    "Banyjima": f"{SW}.banyjima",
    "Ngarluma": f"{SW}.ngarluma",
    "Nyamal": f"{SW}.nyamal",
    "Kariyarra": f"{SW}.kariyarra",
    "Badimaya": f"{SW}.badimaya",
    "Palyku/Nyiyaparli": f"{SW}.palyku",
    "Yinhawangka": f"{SW}.yinhawangka",
    "Ngatjumaya": f"{SW}.ngatjumaya",
    "Mirning": f"{SW}.mirning",
    # Southeastern
    "Wiradjuri": f"{SE}.wiradjuri",
    "Gamilaraay": f"{SE}.gamilaraay",
    "Bandjalang": f"{SE}.bandjalang",
    "Gumbaynggir": f"{SE}.gumbaynggir",
    "Yugambeh": f"{SE}.yugambeh",
    "Yorta Yorta": f"{SE}.yorta_yorta",
    "Dhanggatti": f"{SE}.dhanggatti",
    "Dharawal": f"{SE}.dharawal",
    "Batjala": f"{SE}.batjala",
    "Githabul": f"{SE}.githabul",
    "Muruwari": f"{SE}.muruwari",
    "Djabwurrung": f"{SE}.djabwurrung",
    "Wergaia": f"{SE}.wergaia",
    # other Pama-Nyungan
    "Wik Mungkan": f"{PN}.wik_mungkan",
    "Guugu Yimidhirr": f"{PN}.guugu_yimidhirr",
    "Kuku Yalanji": f"{PN}.kuku_yalanji",
    "Kuuk Thayorre": f"{PN}.kuuk_thayorre",
    "Kuuku-Ya'u": f"{PN}.kuuku_yau",
    "Koko-Bera": f"{PN}.koko_bera",
    "Wik Ngathan": f"{PN}.wik_ngathan",
    "Djabugay": f"{PN}.djabugay",
    "Yidiny": f"{PN}.yidiny",
    "Dyirbal": f"{PN}.dyirbal",
    "Girramay": f"{PN}.girramay",
    "Bidjara": f"{PN}.bidjara",
    "Gudjal": f"{PN}.gudjal",
    "Warumungu": f"{PN}.warumungu",
    "Yanyuwa": f"{PN}.yanyuwa",
    "Adnymathanha": f"{PN}.adnyamathanha",
    "Kaurna": f"{PN}.kaurna",
    "Narungga": f"{PN}.narungga",
    "Arabana": f"{PN}.arabana",
    "Diyari": f"{PN}.diyari",
    "Ngarrindjeri": f"{PN}.ngarrindjeri",
    "Paakantyi": f"{PN}.paakantyi",
    "Kanai": f"{PN}.kanai",
    "Nyangumarta": f"{PN}.nyangumarta",
    "Karajarri": f"{PN}.karajarri",
    "Mangala": f"{PN}.mangala",
    # Gunwinyguan
    "Kunwinjkuan, nec": f"{AU}.gunwinyguan",
    "Kunwinjkuan, nfd": f"{AU}.gunwinyguan",
    "Kunwinjku": f"{AU}.gunwinyguan.kunwinjku",
    "Kune": f"{AU}.gunwinyguan.kune",
    "Kuninjku": f"{AU}.gunwinyguan.kuninjku",
    "Mayali": f"{AU}.gunwinyguan.mayali",
    "Gundjeihmi": f"{AU}.gunwinyguan.gundjeihmi",
    "Anindilyakwa": f"{AU}.gunwinyguan.anindilyakwa",
    "Nunggubuyu": f"{AU}.gunwinyguan.nunggubuyu",
    "Rembarrnga": f"{AU}.gunwinyguan.rembarrnga",
    "Dalabon": f"{AU}.gunwinyguan.dalabon",
    "Ngandi": f"{AU}.gunwinyguan.ngandi",
    "Jawoyn": f"{AU}.gunwinyguan.jawoyn",
    "Kunbarlang": f"{AU}.gunwinyguan.kunbarlang",
    # Maningrida
    "Burarran, nec": f"{AU}.maningrida",
    "Burarran, nfd": f"{AU}.maningrida",
    "Burarra": f"{AU}.maningrida.burarra",
    "Ndjebbana (Gunavidji)": f"{AU}.maningrida.ndjebbana",
    "Na-kara": f"{AU}.maningrida.na_kara",
    "Gun-nartpa": f"{AU}.maningrida.gun_nartpa",
    "Gurr-goni": f"{AU}.maningrida.gurr_goni",
    # other northern families
    "Maung": f"{AU}.iwaidjan.maung",
    "Iwaidja": f"{AU}.iwaidjan.iwaidja",
    "Murrinh Patha": f"{AU}.daly.murrinh_patha",
    "Ngan'gikurunggurr": f"{AU}.daly.ngangikurunggurr",
    "Marrithiyel": f"{AU}.daly.marrithiyel",
    "Maringarr": f"{AU}.daly.maringarr",
    "Marridan (Maridan)": f"{AU}.daly.marridan",
    "Malak Malak": f"{AU}.daly.malak_malak",
    "Tiwi": f"{AU}.tiwi",
    "Larrakiya": f"{AU}.larrakiya",
    "Wagiman": f"{AU}.wagiman",
    "Wardaman": f"{AU}.wardaman",
    "Jingulu": f"{AU}.mirndi.jingulu",
    "Wambaya": f"{AU}.mirndi.wambaya",
    "Gudanji": f"{AU}.mirndi.gudanji",
    "Jaminjung": f"{AU}.mirndi.jaminjung",
    "Ngaliwurru": f"{AU}.mirndi.ngaliwurru",
    "Nungali": f"{AU}.mirndi.nungali",
    "Mangarrayi": f"{AU}.mangarrayi_maran.mangarrayi",
    "Alawa": f"{AU}.mangarrayi_maran.alawa",
    "Marra": f"{AU}.mangarrayi_maran.marra",
    "Garrwa": f"{AU}.garrwan.garrwa",
    "Waanyi": f"{AU}.garrwan.waanyi",
    "Lardil": f"{AU}.tangkic.lardil",
    "Kayardild": f"{AU}.tangkic.kayardild",
    "Miriwoong": f"{AU}.jarrakan.miriwoong",
    "Kija": f"{AU}.jarrakan.kija",
    "Bunuba": f"{AU}.bunuban.bunuba",
    "Gooniyandi": f"{AU}.bunuban.gooniyandi",
    "Bardi": f"{AU}.nyulnyulan.bardi",
    "Nyikina": f"{AU}.nyulnyulan.nyikina",
    "Yawuru": f"{AU}.nyulnyulan.yawuru",
    "Ngarinyin": f"{AU}.worrorran.ngarinyin",
    "Worrorra": f"{AU}.worrorran.worrorra",
    "Wunambal": f"{AU}.worrorran.wunambal",
    "Worla": f"{AU}.worrorran.worla",
    # ---- Other languages ----
    "Acholi": f"{NS}.nilotic.acholi",
    "African Languages, nec": "other",
    "African Languages, nfd": "other",
    "Akan": f"{NC}.kwa.akan",
    "American Languages": "americas_other",
    "Amharic": f"{AA}.ethiosemitic.amharic",
    "Anuak": f"{NS}.nilotic.anuak",
    "Auslan": "signlanguage.auslan",
    "Bari": f"{NS}.nilotic.bari",
    "Bassa": f"{NC}.kru.bassa",
    "Bemba": f"{NC}.bantu.bemba.bemba",
    "Bislama": f"{CR}.english_based.bislama",
    "Dan (Gio-Dan)": f"{NC}.mande.dan",
    "Dinka": f"{NS}.nilotic.dinka",
    "Ewe": f"{NC}.kwa.gbe",
    "Fijian": f"{OC}.fijian",
    "Fulfulde": f"{NC}.atlantic.fulah",
    "Ga": f"{NC}.kwa.ga",
    "Gilbertese": f"{OC}.gilbertese",
    "Harari": f"{AA}.ethiosemitic.harari",
    "Hausa": f"{AA}.chadic.hausa",
    "Igbo": f"{NC}.voltaniger.igbo",
    "Invented Languages": "other",
    "Key Word Sign Australia": "signlanguage.keyword_sign",
    "Kikuyu": f"{NC}.bantu.gikuyu",
    "Kinyarwanda (Rwanda)": f"{NC}.bantu.kinyarwanda",
    "Kirundi (Rundi)": f"{NC}.bantu.kirundi",
    "Kiwai": "papuan.kiwai",
    "Kpelle": f"{NC}.mande.kpelle",
    "Krahn": f"{NC}.kru.krahn",
    "Krio": f"{CR}.english_based.krio",
    "Liberian (Liberian English)": f"{CR}.english_based.liberian",
    "Lingala": f"{NC}.bantu.lingala",
    "Loma (Lorma)": f"{NC}.mande.loma",
    "Luganda": f"{NC}.bantu.ganda",
    "Luo": f"{NS}.nilotic.luo",
    "Madi": f"{NS}.madi",
    "Mandinka": f"{NC}.mande.mandinka",
    "Mann": f"{NC}.mande.mano",
    "Maori (Cook Island)": f"{OC}.cook_islands_maori",
    "Maori (New Zealand)": f"{OC}.maori",
    "Mauritian Creole": f"{CR}.french_based.morisyen",
    "Moro (Nuba Moro)": f"{NC}.moro",
    "Motu (HiriMotu)": f"{OC}.peripheral_papuan_tip.motu",   # pg's node, merged 2026-10-08
    "Nauruan": f"{OC}.nauruan",
    "Ndebele": f"{NC}.bantu.nguni.ndebele_zw",
    "Niue": f"{OC}.niuean",
    "Norf'k-Pitcairn": f"{CR}.english_based.norfuk",
    "Nuer": f"{NS}.nilotic.nuer",
    "Nyanja (Chichewa)": f"{NC}.bantu.nyanja_sena.nyanja",   # zm.txt's; one language
    "Oceanian Pidgins and Creoles, nec": f"{CR}.english_based",
    "Oceanian Pidgins and Creoles, nfd": f"{CR}.english_based",
    "Oromo": f"{AA}.cushitic.lowland.oromo",
    "Other Languages, nfd": "other",
    "Pacific Austronesian Languages, nec": AN,
    "Pacific Austronesian Languages, nfd": AN,
    "Papua New Guinea Languages, nec": "other",
    "Papua New Guinea Languages, nfd": "other",
    "Rotuman": f"{OC}.rotuman",
    "Samoan": f"{OC}.samoan",
    "Seychelles Creole": f"{CR}.french_based.seselwa",
    "Shilluk": f"{NS}.nilotic.shilluk",
    "Shona": f"{NC}.bantu.shona",
    "Sign Languages, nec": "signlanguage",
    "Sign Languages, nfd": "signlanguage",
    "Solomon Islands Pijin": f"{CR}.english_based.pijin",
    "Somali": f"{AA}.cushitic.lowland.somali",
    "Swahili": f"{NC}.bantu.swahili",
    "Themne": f"{NC}.atlantic.temne",
    "Tigre": f"{AA}.ethiosemitic.tigre",
    "Tigrinya": f"{AA}.ethiosemitic.tigrinya",
    "Tok Pisin (Neomelanesian)": f"{CR}.english_based.tok_pisin",
    "Tokelauan": f"{OC}.tokelauan",
    "Tongan": f"{OC}.tongan",
    "Tswana": f"{NC}.bantu.sotho_tswana.setswana",
    "Tuvaluan": f"{OC}.tuvaluan",
    "Xhosa": f"{NC}.bantu.nguni.xhosa",
    "Yapese": f"{OC}.yapese",   # merged with fm/pl's node 2026-10-08
    "Yoruba": f"{NC}.voltaniger.yoruba",
    "Zulu": f"{NC}.bantu.nguni.zulu",
    # ---- supplementary codes ----
    "Swiss, so described": IE,
    "Cypriot, so described": "other",
    "Creole, nfd": CR,
    "French Creole, nfd": f"{CR}.french_based",
    "Spanish Creole, nfd": f"{CR}.spanish_based",
    "Portuguese Creole, nfd": f"{CR}.portuguese_based",
    "Pidgin, nfd": CR,
}

# not drawn: answers that name no language (sources/au.md, gap)
NOT_DRAWN = {"Inadequately described", "Non-verbal, so described"}


def resolve(name):
    if name in NOT_DRAWN:
        return None
    return NAMES[name]
