"""Brazil, Censo 2022, indigenous language spoken at home (Tabela complementar 26) -> node.

Keyed by the census's own label; IBGE's codes and labels are one-to-one (checked in
sources/br_censo.py). Families and branches are IBGE's classification (SIDRA classification
2105, the census's Apêndice 2: Rodrigues' troncos Macro-Jê and Tupi, then families outside the
troncos, isolates, French-based creoles, languages "sem classificação atual determinada", sign
languages, other languages of the Americas). Where Glottolog differs (Guató, Kariri and Yatê are
isolates there; Jabutí sits in Macro-Jê; Aweti is a sister of Tupi-Guarani) the census wins:
it is the Brazilian convention and what the counts were coded against.

Unnamed and family-level labels sit on the narrowest node (spec §3.2):
  Macro-Jê / Jê / Tupi / Aruak / Karib / Pano / Bora / Txapakura / Ramarama "não especificado"
      on their family or branch;
  "Tupi-Guarani (**)", which IBGE footnotes as a family declared as a language, on Tupi-Guarani;
  "Tupi-Mondé", the Mondé family's other name, on Mondé;
  "Timbira" and "Kanela não especificado" on the Timbira and Kanela groups added in
      tree.d/br.txt; "Tupi-Kawahiwa não especificado" on the Kawahiva group;
  "Guarani" on the Guarani group: in Brazil the name covers three languages the census also
      lists (Kaiowá, Mbya, Nhandeva/Avá), and IBGE codes it as their parent (800011 / 8000111x).
  "Kayapó", "Nambikwára", "Yanomami" and "Pakaa Nova (Wari')" stay leaves: each names one
      language, and the labels beside them are its dialects or peoples.
"Outra língua das Américas" (71) is drawn on `other`. "Não determinada", "Mal definida" and
"Não sabe" (2,495 people who speak an indigenous language the census could not name) are not
drawn; countries/br.py leaves them out of Portuguese too and states them in `gap`.
Eñepá is Panare, a Cariban language of Venezuela; IBGE files it under "other languages of the
Americas", the tree under Cariban (Glottolog enap1235).
"""

NAMES = {
    'Mapuche': 'araucanian.mapuche',
    'Aruak não especificado': 'arawakan',
    'Apurinã': 'arawakan.apurina',
    'Ashaninka': 'arawakan.ashaninka',
    'Baniwa': 'arawakan.baniwa',
    'Enawenê-Nawê': 'arawakan.enawene_nawe',
    'Kaixana': 'arawakan.kaixana',
    'Kinikinau': 'arawakan.kinikinau',
    'Kuripako': 'arawakan.kuripako',
    'Manchineri': 'arawakan.manchineri',
    'Mawayána': 'arawakan.mawayana',
    'Mehináku': 'arawakan.mehinaku',
    'Palikur': 'arawakan.palikur',
    'Paresí': 'arawakan.paresi',
    'Tariana': 'arawakan.tariana',
    'Terena': 'arawakan.terena',
    'Wapixana': 'arawakan.wapixana',
    'Warekena': 'arawakan.warekena',
    'Waura': 'arawakan.waura',
    'Wayuu': 'arawakan.wayuu',
    'Yawalapití': 'arawakan.yawalapiti',
    'Arawá': 'arawan.arawa',
    'Banawá': 'arawan.banawa',
    'Dení': 'arawan.deni',
    'Jamamadi': 'arawan.jamamadi',
    'Jarawára': 'arawan.jarawara',
    'Kulina Madijá': 'arawan.kulina_madija',
    'Paumarí': 'arawan.paumari',
    'Suruwaha': 'arawan.suruwaha',
    'Aimara': 'aymaran.aymara',
    'Bora não especificado': 'boran',
    'Miránha': 'boran.miranha',
    'Karib não especificado': 'cariban',
    'Akawaio': 'cariban.akawaio',
    'Akuriyó': 'cariban.akuriyo',
    'Apalai': 'cariban.apalai',
    'Arara do Pará': 'cariban.arara_do_para',
    'Arekuna': 'cariban.arekuna',
    'Bakairi': 'cariban.bakairi',
    'Eñepá': 'cariban.enepa',
    "Faruk'woto": 'cariban.faruk_woto',
    "Galibi Kali'na": 'cariban.galibi_kali_na',
    'Hixkaryana': 'cariban.hixkaryana',
    'Ikpeng': 'cariban.ikpeng',
    'Ingarikó': 'cariban.ingariko',
    'Kalapalo': 'cariban.kalapalo',
    'Kamarakoto': 'cariban.kamarakoto',
    'Katwena': 'cariban.katwena',
    'Katxuyana': 'cariban.katxuyana',
    'Kuikuro': 'cariban.kuikuro',
    'Makuxí': 'cariban.makuxi',
    'Matipú': 'cariban.matipu',
    'Nahukuá': 'cariban.nahukua',
    'Patamóna': 'cariban.patamona',
    'Taurepang': 'cariban.taurepang',
    'Tiriyó': 'cariban.tiriyo',
    'Tunayana': 'cariban.tunayana',
    'Wai Wai': 'cariban.wai_wai',
    'Waimiri Atroari': 'cariban.waimiri_atroari',
    'Wayana': 'cariban.wayana',
    'Xerewyana': 'cariban.xerewyana',
    "Ye'kwana": 'cariban.ye_kwana',
    'Txapakura não especificado': 'chapacuran',
    'Kujubim': 'chapacuran.kujubim',
    'Oro At': 'chapacuran.oro_at',
    'Oro Eo': 'chapacuran.oro_eo',
    'Oro Mon': 'chapacuran.oro_mon',
    'Oro Náo': 'chapacuran.oro_nao',
    'Oro Waram': 'chapacuran.oro_waram',
    'Oro Waram Xijein': 'chapacuran.oro_waram_xijein',
    'Oro Win': 'chapacuran.oro_win',
    "Pakaa Nova (Wari')": 'chapacuran.pakaa_nova',
    'Torá (*)': 'chapacuran.tora',
    'Chiquitáno': 'chiquitano.chiquitano',
    'Creole do Amapá': 'creole.french_based.creole_do_amapa',
    'Kheuól Galibí Marwórno': 'creole.french_based.kheuol_galibi_marworno',
    'Kheuól Karipuna': 'creole.french_based.kheuol_karipuna',
    'Patuá (Crioula)': 'creole.french_based.patua',
    'Kadiwéu': 'guaicuruan.kadiweu',
    'Aikanã': 'isolate.aikana',
    'Akroá Gamela': 'isolate.akroa_gamela',
    'Guató': 'isolate.guato',
    'Irántxe': 'isolate.irantxe',
    'Kanoé': 'isolate.kanoe',
    'Kwazá': 'isolate.kwaza',
    'Menkü (Myky Manoki)': 'isolate.menku',
    "Ruãynyn'reue": 'isolate.ruaynyn_reue',
    'Tikúna': 'isolate.tikuna',
    'Trumái': 'isolate.trumai',
    'Warao': 'isolate.warao',
    'Xukuru': 'isolate.xukuru',
    'Xukurú-Kariri': 'isolate.xukuru_kariri',
    'Arikapú': 'jabutian.arikapu',
    'Djeoromitxí-Jaboti': 'jabutian.djeoromitxi_jaboti',
    'Kanamarí': 'katukinan.kanamari',
    'Katawixí': 'katukinan.katawixi',
    'Katukina do Rio Biá (Pedá Djapá)': 'katukinan.katukina_do_rio_bia',
    'Macro-Jê não especificado': 'macroje',
    'Bororo': 'macroje.bororo.bororo',
    'Umutina': 'macroje.bororo.umutina',
    'Brobó': 'macroje.brobo.brobo',
    'Jê não especificado': 'macroje.je',
    'Apinayé': 'macroje.je.apinaye',
    'Kaingang': 'macroje.je.kaingang',
    'Kayapó': 'macroje.je.kayapo',
    'Kisêdjê': 'macroje.je.kisedje',
    'Mebêngôkre Kayapó': 'macroje.je.mebengokre_kayapo',
    'Menkrangnoti': 'macroje.je.menkrangnoti',
    'Mentuktire': 'macroje.je.mentuktire',
    'Panará': 'macroje.je.panara',
    'Tapayuna': 'macroje.je.tapayuna',
    'Timbira': 'macroje.je.timbira',
    'Gavião Kykatejê': 'macroje.je.timbira.gaviao_kykateje',
    'Gavião Parkatêjê': 'macroje.je.timbira.gaviao_parkateje',
    'Gavião Pykopjê': 'macroje.je.timbira.gaviao_pykopje',
    'Kanela não especificado': 'macroje.je.timbira.kanela',
    'Kanela Apanyekrá': 'macroje.je.timbira.kanela.apanyekra',
    'Kanela Rankokamekrá': 'macroje.je.timbira.kanela.rankokamekra',
    'Krahô': 'macroje.je.timbira.kraho',
    'Kreepyn-Katejê': 'macroje.je.timbira.kreepyn_kateje',
    'Krenyê': 'macroje.je.timbira.krenye',
    'Krikati': 'macroje.je.timbira.krikati',
    'Xacriabá': 'macroje.je.xacriaba',
    'Xavante': 'macroje.je.xavante',
    'Xerente': 'macroje.je.xerente',
    'Xikrin': 'macroje.je.xikrin',
    'Xokléng': 'macroje.je.xokleng',
    'Kamakã': 'macroje.kamaka.kamaka',
    'Karajá': 'macroje.karaja.karaja',
    'Karajá Javaé': 'macroje.karaja.karaja_javae',
    'Xambioá': 'macroje.karaja.xambioa',
    'Dzubokuá': 'macroje.kariri.dzubokua',
    'Kariri': 'macroje.kariri.kariri',
    'Kipéa': 'macroje.kariri.kipea',
    'Xocó': 'macroje.kariri.xoco',
    'Krenák': 'macroje.krenak.krenak',
    'Maxakali': 'macroje.maxakali.maxakali',
    'Pataxó': 'macroje.maxakali.pataxo',
    'Pataxó Hã-Hã-Hãe': 'macroje.maxakali.pataxo_ha_ha_hae',
    'Ofayé': 'macroje.ofaye.ofaye',
    'Rikbaktsa': 'macroje.rikbaktsa.rikbaktsa',
    'Yathê': 'macroje.yate.yathe',
    'Múra': 'muran.mura',
    'Pirahã': 'muran.piraha',
    'Warapakai': 'muran.warapakai',
    'Dâw': 'nadahup.daw',
    "Hupd'äh": 'nadahup.hupd_ah',
    'Nadëb': 'nadahup.nadeb',
    'Puinave': 'nadahup.puinave',
    'Yuhupdëh': 'nadahup.yuhupdeh',
    'Alantesú': 'nambikwaran.alantesu',
    'Hahaintesu': 'nambikwaran.hahaintesu',
    'Halotesu': 'nambikwaran.halotesu',
    'Kithaulu': 'nambikwaran.kithaulu',
    'Latundê': 'nambikwaran.latunde',
    'Mamaindê': 'nambikwaran.mamainde',
    'Manduka': 'nambikwaran.manduka',
    'Nambikwára': 'nambikwaran.nambikwara',
    'Negarotê': 'nambikwaran.negarote',
    'Sabanê': 'nambikwaran.sabane',
    'Tawandê': 'nambikwaran.tawande',
    'Waikisu': 'nambikwaran.waikisu',
    'Wasusu': 'nambikwaran.wasusu',
    'Outra língua das Américas': 'other',
    'Pano não especificado': 'panoan',
    'Arara do Acre (Arara Shawãdawa)': 'panoan.arara_do_acre',
    'Kaxarari': 'panoan.kaxarari',
    'Kaxinawá': 'panoan.kaxinawa',
    'Korubo': 'panoan.korubo',
    'Kulina Pano': 'panoan.kulina_pano',
    'Marúbo': 'panoan.marubo',
    'Mastanawa': 'panoan.mastanawa',
    'Matís': 'panoan.matis',
    'Matsés': 'panoan.matses',
    'Mayoruna': 'panoan.mayoruna',
    'Noke Vana': 'panoan.noke_vana',
    'Nukiní': 'panoan.nukini',
    'Poyanáwa': 'panoan.poyanawa',
    'Shanenáwa': 'panoan.shanenawa',
    'Yamináwa': 'panoan.yaminawa',
    'Yawanawá': 'panoan.yawanawa',
    'Quechua': 'quechuan.quechua',
    'Quíchua': 'quechuan.quichua',
    'Língua de Sinais Kiriri': 'signlanguage.kiriri',
    'Língua de Sinais Terena': 'signlanguage.terena',
    'Língua de Sinais Urubu Ka’apor': 'signlanguage.urubu_kaapor',
    'Arapaso': 'tucanoan.arapaso',
    'Bará': 'tucanoan.bara',
    'Barasána': 'tucanoan.barasana',
    'Desána': 'tucanoan.desana',
    'Karapanã': 'tucanoan.karapana',
    'Kubeo': 'tucanoan.kubeo',
    'Makúna': 'tucanoan.makuna',
    'Mirititapuia': 'tucanoan.mirititapuia',
    'Piratapuia (Waikhana)': 'tucanoan.piratapuia',
    'Siriano (Siriãmahsã)': 'tucanoan.siriano',
    'Tanimuka': 'tucanoan.tanimuka',
    'Tukano': 'tucanoan.tukano',
    'Tuyúca': 'tucanoan.tuyuca',
    'Wanano': 'tucanoan.wanano',
    'Tupi não especificado': 'tupian',
    'Karitiana': 'tupian.arikem.karitiana',
    'Xipáya': 'tupian.juruna.xipaya',
    'Yudjá': 'tupian.juruna.yudja',
    'Sateré-Mawé': 'tupian.mawe.satere_mawe',
    'Tupi-Mondé': 'tupian.monde',
    'Aruá': 'tupian.monde.arua',
    'Gavião de Rondônia': 'tupian.monde.gaviao_de_rondonia',
    'Paiter': 'tupian.monde.paiter',
    'Salamãy': 'tupian.monde.salamay',
    'Zoró': 'tupian.monde.zoro',
    'Kuruáya': 'tupian.munduruku.kuruaya',
    'Munduruku': 'tupian.munduruku.munduruku',
    'Puroborá': 'tupian.purubora.purobora',
    'Ramarama não especificado': 'tupian.ramarama',
    'Arara de Rondônia (Arara Karo)': 'tupian.ramarama.arara_de_rondonia',
    'Ajuru': 'tupian.tupari.ajuru',
    'Akuntsu': 'tupian.tupari.akuntsu',
    'Makuráp': 'tupian.tupari.makurap',
    'Sakurabiat': 'tupian.tupari.sakurabiat',
    'Tuparí': 'tupian.tupari.tupari',
    'Tupi-Guarani (**)': 'tupian.tupiguarani',
    'Amanayé': 'tupian.tupiguarani.amanaye',
    'Anambé': 'tupian.tupiguarani.anambe',
    'Apiaká': 'tupian.tupiguarani.apiaka',
    'Araweté': 'tupian.tupiguarani.arawete',
    'Asurini do Tocantins': 'tupian.tupiguarani.asurini_do_tocantins',
    'Asurini do Xingu': 'tupian.tupiguarani.asurini_do_xingu',
    'Avá-Canoeiro': 'tupian.tupiguarani.ava_canoeiro',
    'Awa Guajá': 'tupian.tupiguarani.awa_guaja',
    'Aweti': 'tupian.tupiguarani.aweti',
    'Guajajara': 'tupian.tupiguarani.guajajara',
    'Guarani': 'tupian.tupiguarani.guarani',
    'Avá Guarani': 'tupian.tupiguarani.guarani.ava_guarani',
    'Guarani Kaiowá': 'tupian.tupiguarani.guarani.kaiowa',
    'Guarani Mbya': 'tupian.tupiguarani.guarani.mbya',
    'Guarani Nhandeva': 'tupian.tupiguarani.guarani.nhandeva',
    "Ka'apor": 'tupian.tupiguarani.ka_apor',
    'Kaiabi (Kawaiwete)': 'tupian.tupiguarani.kaiabi',
    'Kamayurá': 'tupian.tupiguarani.kamayura',
    'Kambéba': 'tupian.tupiguarani.kambeba',
    'Tupi-Kawahiwa não especificado': 'tupian.tupiguarani.kawahiva',
    'Jiahui': 'tupian.tupiguarani.kawahiva.jiahui',
    'Juma': 'tupian.tupiguarani.kawahiva.juma',
    'Kawahíba dos Amondáwa': 'tupian.tupiguarani.kawahiva.kawahiba_dos_amondawa',
    'Kawahíba dos Karipuna': 'tupian.tupiguarani.kawahiva.kawahiba_dos_karipuna',
    'Parintintim': 'tupian.tupiguarani.kawahiva.parintintim',
    'Tenharim': 'tupian.tupiguarani.kawahiva.tenharim',
    'Kokama': 'tupian.tupiguarani.kokama',
    'Nheengatu': 'tupian.tupiguarani.nheengatu',
    'Parakanã (Awaeté Xeenga)': 'tupian.tupiguarani.parakana',
    'Suruí do Pará': 'tupian.tupiguarani.surui_do_para',
    'Tapirapé': 'tupian.tupiguarani.tapirape',
    'Tembé': 'tupian.tupiguarani.tembe',
    'Tenetehára': 'tupian.tupiguarani.tenetehara',
    'Tupi-Potiguara': 'tupian.tupiguarani.tupi_potiguara',
    'Wajãpi': 'tupian.tupiguarani.wajapi',
    'Xetá': 'tupian.tupiguarani.xeta',
    "Zo'é": 'tupian.tupiguarani.zo_e',
    'Aconã': 'unclassified.acona',
    'Anacé': 'unclassified.anace',
    'Arapium': 'unclassified.arapium',
    'Atikum': 'unclassified.atikum',
    'Borari': 'unclassified.borari',
    'Botocudo (*)': 'unclassified.botocudo',
    'Bremem Taipwenya': 'unclassified.bremem_taipwenya',
    'Kaimbé': 'unclassified.kaimbe',
    'Kambiwá': 'unclassified.kambiwa',
    'Kambiwá-Pipipã': 'unclassified.kambiwa_pipipa',
    'Kanindé': 'unclassified.kaninde',
    'Kapinawá': 'unclassified.kapinawa',
    'Karapotó': 'unclassified.karapoto',
    'Kariri-Xocó': 'unclassified.kariri_xoco',
    'Kaxixó': 'unclassified.kaxixo',
    'Kiriri': 'unclassified.kiriri',
    'Kumaruara': 'unclassified.kumaruara',
    'Kwaytikindo (Puri)': 'unclassified.kwaytikindo',
    'Maraguá': 'unclassified.maragua',
    'Maytapu': 'unclassified.maytapu',
    'Nawa': 'unclassified.nawa',
    'Paiaku (Jenipapo-Kanindé)': 'unclassified.paiaku',
    'Pankará': 'unclassified.pankara',
    'Pankararé': 'unclassified.pankarare',
    'Pankararú': 'unclassified.pankararu',
    'Pitaguari': 'unclassified.pitaguari',
    'Sabujá': 'unclassified.sabuja',
    'Tabajara': 'unclassified.tabajara',
    'Tapajós (*)': 'unclassified.tapajos',
    'Tapeba': 'unclassified.tapeba',
    'Tapuia': 'unclassified.tapuia',
    'Tremembé': 'unclassified.tremembe',
    'Truká': 'unclassified.truka',
    'Tupinambá': 'unclassified.tupinamba',
    'Tupinambarana': 'unclassified.tupinambarana',
    'Tupiniquim': 'unclassified.tupiniquim',
    'Tuxá': 'unclassified.tuxa',
    'Tuxi': 'unclassified.tuxi',
    'Wassú': 'unclassified.wassu',
    'Ybutritê': 'unclassified.ybutrite',
    'Ypy': 'unclassified.ypy',
    'Witóto': 'witotoan.witoto',
    'Ninám': 'yanomaman.ninam',
    'Sanumá': 'yanomaman.sanuma',
    'Xiriana': 'yanomaman.xiriana',
    'Xirixana': 'yanomaman.xirixana',
    'Yanomami': 'yanomaman.yanomami',
    'Yanomán': 'yanomaman.yanoman',
    'Mal definida': None,
    'Não determinada': None,
    'Não sabe': None,}

# resolve() returns this, which is not a table value: everyone else in the município
EXTRA_NODES = ["indoeuropean.romance.portuguese"]


def resolve(name):
    return NAMES[name]
