"""Nepal NPHC 2021 mother tongue -> node. Keyed by the census's own spelling.

`Not stated` (168 people) is not drawn. `Others` (33,621) is drawn on `other`.
`Rai` (143,797) is a community name over a dozen Kiranti languages, so it sits on Kiranti.
`Musalman` (15,745) is the census's name for the speech of Terai Muslims who did not answer
Urdu; it is an Awadhi/Bhojpuri-like Hindustani, drawn on Central (Western Hindi) with Urdu's
group rather than guessed into either.
"""
IA = "indoeuropean.indoaryan"
ST = "sinotibetan"

NAMES = {
    "Nepali": f"{IA}.pahari.eastern.nepali",
    "Maithili": f"{IA}.bihari.maithili",
    "Bhojpuri": f"{IA}.bihari.bhojpuri",
    "Tharu": f"{IA}.tharu.tharu",
    "Tamang": f"{ST}.tamangic.tamang",
    "Bajjika": f"{IA}.bihari.bajjika",
    "Nepalbhasha(Newari)": f"{ST}.newaric.newar",
    "Avadhi": f"{IA}.eastcentral.awadhi",
    "Magar Dhut": f"{ST}.magaric.magar_dhut",
    "Doteli": f"{IA}.pahari.eastern.doteli",
    "Urdu": f"{IA}.central.urdu",
    "Yakthung/Limbu": f"{ST}.kiranti.limbu",
    "Gurung": f"{ST}.tamangic.gurung",
    "Magahi": f"{IA}.bihari.magahi",
    "Baitadeli": f"{IA}.pahari.eastern.baitadeli",
    "Rai": f"{ST}.kiranti.rai",
    "Achhami": f"{IA}.pahari.eastern.achhami",
    "Bantawa": f"{ST}.kiranti.bantawa",
    "Rajbanshi": f"{IA}.eastern.rajbanshi",
    "Sherpa": f"{ST}.tibetic.sherpa",
    "Khash": f"{IA}.pahari.eastern.khash",
    "Bajhangi": f"{IA}.pahari.eastern.bajhangi",
    "Hindi": f"{IA}.central.hindi",
    "Magar Kham": f"{ST}.magaric.magar_kham",
    "Chamling": f"{ST}.kiranti.chamling",
    "Ranatharu": f"{IA}.tharu.rana",
    "Chepang": f"{ST}.chepangic.chepang",
    "Bajureli": f"{IA}.pahari.eastern.bajureli",
    "Santhali": "austroasiatic.munda.santali",
    "Danuwar": f"{IA}.inner_terai.danuwar",
    "Darchuleli": f"{IA}.pahari.eastern.darchuleli",
    "Uranw/Urau": "dravidian.northern.kurukh",
    "Kulung": f"{ST}.kiranti.kulung",
    "Angika": f"{IA}.bihari.angika",
    "Others": "other",
    "Majhi": f"{IA}.inner_terai.majhi",
    "Sunuwar": f"{ST}.kiranti.sunuwar",
    "Thami": f"{ST}.newaric.thangmi",
    "Ganagai": f"{IA}.bihari.angika",           # Ganagai is an Angika variety of Morang and Sunsari
    "Thulung": f"{ST}.kiranti.thulung",
    "Bangla": f"{IA}.eastern.bengali",
    "Ghale": f"{ST}.tamangic.ghale",
    "Sampang": f"{ST}.kiranti.sampang",
    "Dadeldhuri": f"{IA}.pahari.eastern.dadeldhuri",
    "Marwadi": f"{IA}.rajasthani.marwari",
    "Dhimal": f"{ST}.dhimalish.dhimal",
    "Tajpuriya": f"{IA}.eastern.tajpuriya",
    "Kumal": f"{IA}.inner_terai.kumal",
    "Khaling": f"{ST}.kiranti.khaling",
    "Musalman": f"{IA}.central.musalman",
    "Wambule": f"{ST}.kiranti.wambule",
    "Bahing/Bayung": f"{ST}.kiranti.bahing",
    "Yakkha": f"{ST}.kiranti.yakkha",
    "Sanskrit": f"{IA}.sanskrit",
    "Bhote": f"{ST}.tibetic.bhote",
    "Bhujel": f"{ST}.chepangic.bhujel",
    "Darai": f"{IA}.inner_terai.darai",
    "Yamphu/Yamphe": f"{ST}.kiranti.yamphu",
    "Nachhiring": f"{ST}.kiranti.nachhiring",
    "Hyolmo/Yholmo": f"{ST}.tibetic.hyolmo",
    "Dumi": f"{ST}.kiranti.dumi",
    "Jumli": f"{IA}.pahari.eastern.jumli",
    "Bote": f"{IA}.inner_terai.bote",
    "Mewahang": f"{ST}.kiranti.mewahang",
    "Puma": f"{ST}.kiranti.puma",
    "Pahari": f"{ST}.newaric.pahari",                  # Nepal's Pahari is the Newar-related speech of the Pahari caste
    "Athpahariya": f"{ST}.kiranti.athpahariya",
    "Dungmali": f"{ST}.kiranti.dungmali",
    "Jirel": f"{ST}.tibetic.jirel",
    "Tibetan": f"{ST}.tibetic.tibetan",
    "Dailekhi": f"{IA}.pahari.eastern.dailekhi",
    "Chum/Nubri": f"{ST}.tibetic.nubri",
    "Raji": f"{ST}.westhimalayish.raji",
    "Chhantyal": f"{ST}.tamangic.chhantyal",
    "Meche": f"{ST}.boro_garo.mech",
    "Koyee": f"{ST}.kiranti.koyee",
    "Thakali": f"{ST}.tamangic.thakali",
    "Lohorung": f"{ST}.kiranti.lohorung",
    "Kewarat": f"{IA}.kewarat",
    "Dolpali": f"{IA}.pahari.eastern.dolpali",
    "Done": f"{IA}.done",
    "Mugali": f"{IA}.pahari.eastern.mugali",
    "Jero/Jerung": f"{ST}.kiranti.jerung",
    "Karmarong": f"{ST}.tibetic.karmarong",
    "Chhintang": f"{ST}.kiranti.chhintang",
    "Lhopa": f"{ST}.tibetic.lhopa",
    "Lapcha": f"{ST}.lepcha",
    "Munda/Mudiyari": "austroasiatic.munda.mundari",
    "Dura": f"{ST}.dura",
    "Chhiling": f"{ST}.kiranti.chhiling",
    "Tilung": f"{ST}.kiranti.tilung",
    "Manange": f"{ST}.tamangic.manange",
    "Byansi": f"{ST}.westhimalayish.byansi",
    "Baragunwa": f"{ST}.tibetic.baragaunle",              # Baragaunle, the Tibetan speech of upper Mustang's twelve villages
    "Balkura/Baram": f"{ST}.newaric.baram",
    "Sadri": f"{IA}.bihari.sadri",
    "Sonaha": f"{IA}.tharu.sonaha",
    "Magar Kaike": f"{ST}.magaric.kaike",
    "Sign Language": "signlanguage",
    "Hayu/Vayu": f"{ST}.kiranti.hayu",
    "Kisan": "dravidian.northern.kurukh",
    "English": "indoeuropean.germanic.english",
    "Khamchi(Raute)": f"{ST}.westhimalayish.raute",
    "Dhuleli": f"{IA}.dhuleli",
    "Punjabi": f"{IA}.northwestern.punjabi",
    "Lungkhim": f"{ST}.kiranti.lungkhim",
    "Lowa": f"{ST}.tibetic.lowa",
    "Kagate": f"{ST}.tibetic.kagate",
    "Nar-Phu": f"{ST}.tamangic.narphu",
    "Tichhurong Poike": f"{ST}.tibetic.tichurong",
    "Waling/Walung": f"{ST}.tibetic.walung",
    "Lhomi": f"{ST}.tibetic.lhomi",
    "Kurmali": f"{IA}.bihari.kurmali",
    "Koche": f"{ST}.boro_garo.koch",
    "Phangduwali": f"{ST}.kiranti.phangduwali",
    "Sindhi": f"{IA}.northwestern.sindhi",
    "Not stated": None,
    "Belhare": f"{ST}.kiranti.belhare",
    "Malpande": f"{IA}.malpande",
    "Surel": f"{ST}.kiranti.surel",
    "Khariya": "austroasiatic.munda.kharia",
    "Sadhani": f"{IA}.bihari.sadri",
    "Sam": f"{ST}.kiranti.sam",
    "Hariyanwi": f"{IA}.central.haryanvi",
    "Bankariya": f"{ST}.chepangic.bankariya",
    "Kusunda": "other",
}


def resolve(name):
    return NAMES[name]
