"""Poland, NSP 2021, language used at home -> node. Keyed by GUS's own spelling (TABL.1/2).

The list GUS printed is long because the online form offered a list of world languages: its
alphabetical head (Abkhaz 446, Acholi 576, Afar 541, Adyghe 836) reads like the top of a
drop-down picked in passing. Every label is still drawn as printed (spec §3.1); sources/pl.md
says why and what it would take to drop them.

Calls (sources/pl.md says more):
  * "gwara śląska" (Silesian dialect, 130) merges into "śląski" (Silesian, 467,145): the same
    speech, the respondent's word "dialect" against "language" being the only difference. The
    other gwary are kept apart, each its own node beside Polish: Cieszyn, Goral, Kociewie,
    Greater Poland (Poznań), Kurpie.
  * "azerski" and "azerbejdżański" are two Polish names for Azerbaijani; "pilipino" and
    "filipiński" two for Filipino; "lushai" is the old name for Mizo; "bini" is Edo; "twi" and
    "fanti" are Akan; "ewe" and "fon" go on the tree's one Gbe node, which names both.
  * Labels naming a group, not a language, sit on that group (as us2024, uk2021 and ca2021 put
    unspecified Chinese): chiński (Chinese), dolnoniemiecki (Low German, whose children are
    Plautdietsch and Low Saxon), malgaski (Malagasy), slavey, guarani, bihari, irański
    (Iranian), hmong-mien.
  * "ruski" (2,297, mostly in the big cities) is its own node: in Polish it is the old word for
    Ruthenian and the colloquial word for Russian, and GUS prints Russian (rosyjski), Lemko and
    Belarusian separately, so neither reading can be assumed.
  * "różne inne gwary regionalne i lokalne" (various other regional and local dialects, 446)
    sits on Slavic: GUS's named gwary are Polish and Podlachian (East Slavic), so Slavic is the
    narrowest node holding what it could have filed there. "inne - niesklasyfikowane" is `other`.
  * "tonga" is taken as Tongan (ISO 639-2 `ton`), the only Tonga in the list; "cziczewa" as Chewa.
"""
IE = "indoeuropean"
GE = f"{IE}.germanic"
CW = f"{GE}.continental"
NG = f"{GE}.north"
RO = f"{IE}.romance"
SL = f"{IE}.slavic"
SE, SW, SS = f"{SL}.east", f"{SL}.west", f"{SL}.south"
BA, CE = f"{IE}.baltic", f"{IE}.celtic"
IA, IR = f"{IE}.indoaryan", f"{IE}.iranian"
AA, AN = "afroasiatic", "austronesian"
OC, PH = f"{AN}.oceanic", f"{AN}.philippine"
NC = "nigercongo"
BT = f"{NC}.bantu"
NS = f"{BT}.nguni"
SO = f"{BT}.sotho_tswana"
ND = "nadene.northern"
ST = "sinotibetan"
TK = "turkic"
UR = "uralic"
NK = "nakhdaghestanian"
NW = "abkhazadyghe"
CR = "creole"

NAMES = {
    "Polski": f"{SW}.polish",
    # ---- West Slavic: Polish's neighbours and its dialects ----
    "śląski": f"{SW}.silesian",
    "gwara śląska": f"{SW}.silesian",
    "kaszubski": f"{SW}.kashubian",
    "gwara cieszyńska": f"{SW}.cieszyn",
    "gwara góralska": f"{SW}.goral",
    "gwara kociewski": f"{SW}.kociewie",
    "gwara wielkopolska (poznańska)": f"{SW}.greater_poland",
    "kurpiowski": f"{SW}.kurpie",
    "czeski": f"{SW}.czech",
    "słowacki": f"{SW}.slovak",
    "górnołużycki": f"{SW}.upper_sorbian",
    "dolnołużycki": f"{SW}.lower_sorbian",
    "różne inne gwary regionalne i lokalne": SL,
    # ---- East Slavic ----
    "rosyjski": f"{SE}.russian",
    "ukraiński": f"{SE}.ukrainian",
    "białoruski": f"{SE}.belarusian",
    "łemkowski": f"{SE}.lemko",
    "ruski": f"{SE}.ruski",
    "gwary podlaskie (polsko-białorusko-ukraińskie)": f"{SE}.podlachian",
    # ---- South Slavic ----
    "bułgarski": f"{SS}.bulgarian",
    "chorwacki": f"{SS}.croatian",
    "serbski": f"{SS}.serbian",
    "serbskochorwacki": f"{SS}.serbocroatian",
    "bośniacki": f"{SS}.bosnian",
    "macedoński": f"{SS}.macedonian",
    "słoweński": f"{SS}.slovenian",
    # ---- Baltic, Celtic, Hellenic, Albanian, Armenian ----
    "litewski": f"{BA}.lithuanian",
    "łotewski": f"{BA}.latvian",
    "irlandzki": f"{CE}.irish",
    "walijski": f"{CE}.welsh",
    "bretoński": f"{CE}.breton",
    "manx": f"{CE}.manx",
    "grecki": f"{IE}.hellenic.greek",
    "albański": f"{IE}.albanian.albanian",
    "ormiański": f"{IE}.armenian.armenian",
    # ---- Germanic ----
    "angielski": f"{GE}.english",
    "szkocki": f"{GE}.scots",
    "fryzyjski": f"{GE}.frisian",
    "niemiecki": f"{CW}.german",
    "niderlandzki": f"{CW}.dutch",
    "flamandzki": f"{CW}.flemish",
    "afrykanerski": f"{CW}.afrikaans",
    "jidysz": f"{CW}.yiddish",
    "dolnoniemiecki": f"{CW}.lowgerman",
    "alemański": f"{CW}.alemannic",
    "alzacki": f"{CW}.alsatian",
    "limburgijski": f"{CW}.limburgish",
    "luksemburski": f"{CW}.luxembourgish",
    "wilamowski": f"{CW}.wymysorys",
    "duński": f"{NG}.danish",
    "norweski": f"{NG}.norwegian",
    "szwedzki": f"{NG}.swedish",
    "islandzki": f"{NG}.icelandic",
    "farerski": f"{NG}.faroese",
    # ---- Romance ----
    "francuski": f"{RO}.french",
    "włoski": f"{RO}.italian",
    "hiszpański": f"{RO}.spanish",
    "portugalski": f"{RO}.portuguese",
    "rumuński": f"{RO}.romanian",
    "mołdawski": f"{RO}.moldovan",
    "kataloński": f"{RO}.catalan",
    "retoromański": f"{RO}.rhaetoromance",
    "aragoński": f"{RO}.aragonese",
    "arumuński": f"{RO}.aromanian",
    "asturyjski": f"{RO}.asturian",
    "friulski": f"{RO}.friulian",
    "galisyjski": f"{RO}.galician",
    "korsykański": f"{RO}.corsican",
    "ladino": f"{RO}.ladino",
    "mirandyjski": f"{RO}.mirandese",
    "neapolitański": f"{RO}.neapolitan",
    "sardyński": f"{RO}.sardinian",
    "sycylijski": f"{RO}.sicilian",
    "waloński": f"{RO}.walloon",
    # ---- Indo-Aryan ----
    "romski": f"{IA}.romani.romani",
    "hindi": f"{IA}.central.hindi",
    "urdu": f"{IA}.central.urdu",
    "bradź": f"{IA}.central.braj",
    "awadhi": f"{IA}.eastcentral.awadhi",
    "bihari": f"{IA}.bihari",
    "angika": f"{IA}.bihari.angika",
    "bhodźpuri": f"{IA}.bihari.bhojpuri",
    "magahi": f"{IA}.bihari.magahi",
    "maithili": f"{IA}.bihari.maithili",
    "bengalski": f"{IA}.eastern.bengali",
    "assamski": f"{IA}.eastern.assamese",
    "orija": f"{IA}.eastern.odia",
    "bisznuprija-manipuri": f"{IA}.eastern.bishnupriya",
    "pendżabski": f"{IA}.northwestern.punjabi",
    "sindhi": f"{IA}.northwestern.sindhi",
    "dogri": f"{IA}.northwestern.dogri",
    "gudźarati": f"{IA}.gujarati.gujarati",
    "marathi": f"{IA}.southern.marathi",
    "konkani": f"{IA}.southern.konkani",
    "radźasthani": f"{IA}.rajasthani.rajasthani",
    "marwari": f"{IA}.rajasthani.marwari",
    "nepali": f"{IA}.pahari.eastern.nepali",
    "kaszmirski": f"{IA}.dardic.kashmiri",
    "syngaleski": f"{IA}.sinhala",
    "divehi": f"{IA}.dhivehi",
    # ---- Iranian ----
    "irański": IR,
    "perski": f"{IR}.persian",
    "kurdyjski": f"{IR}.kurdish",
    "pasztuński": f"{IR}.pashto",
    "beludżi": f"{IR}.balochi",
    "osetyjski": f"{IR}.ossetian",
    "tadżycki": f"{IR}.tajik",
    "zazaki": f"{IR}.zazaki",
    # ---- Uralic ----
    "węgierski": f"{UR}.hungarian",
    "fiński": f"{UR}.finnish",
    "estoński": f"{UR}.estonian",
    "karelski": f"{UR}.karelian",
    "lapoński (saami)": f"{UR}.saami",
    "komi": f"{UR}.komi",
    "udmurcki": f"{UR}.udmurt",
    "maryjski": f"{UR}.mari",
    "erzja": f"{UR}.erzya",
    "moksza": f"{UR}.moksha",
    "selkupski": f"{UR}.selkup",
    # ---- Turkic, Mongolic, Tungusic ----
    "turecki": f"{TK}.turkish",
    "azerbejdżański": f"{TK}.azerbaijani",
    "azerski": f"{TK}.azerbaijani",
    "kazachski": f"{TK}.kazakh",
    "uzbecki": f"{TK}.uzbek",
    "ujgurski": f"{TK}.uyghur",
    "tatarski": f"{TK}.tatar",
    "krymskotatarski": f"{TK}.crimean_tatar",
    "karaimski": f"{TK}.karaim",
    "kirgiski": f"{TK}.kyrgyz",
    "turkmeński": f"{TK}.turkmen",
    "baszkirski": f"{TK}.bashkir",
    "czuwaski": f"{TK}.chuvash",
    "jakucki": f"{TK}.yakut",
    "ałtajski": f"{TK}.altai",
    "tuwiński": f"{TK}.tuvan",
    "karaczajsko-bałkarski": f"{TK}.karachay_balkar",
    "karakałpacki": f"{TK}.karakalpak",
    "kumyk": f"{TK}.kumyk",
    "nogajski": f"{TK}.nogai",
    "mongolski": "mongolic.mongolian",
    "buriacki": "mongolic.buryat",
    "kałmucki": "mongolic.kalmyk",
    "mandżurski": "tungusic.manchu",
    # ---- Caucasus ----
    "gruziński": "kartvelian.georgian",
    "abchaski": f"{NW}.abkhaz",
    "adygejski": f"{NW}.adyghe",
    "kabardyjski": f"{NW}.kabardian",
    "czeczeński": f"{NK}.nakh.chechen",
    "inguski": f"{NK}.nakh.ingush",
    "awarski": f"{NK}.avarandic.avar",
    "dargwijski": f"{NK}.dargwa",
    "lezgiński": f"{NK}.lezgic.lezgian",
    # ---- Afroasiatic ----
    "arabski": f"{AA}.arabic",
    "żydowsko-arabski": f"{AA}.judeo_arabic",
    "hebrajski": f"{AA}.hebrew",
    "aramejski": f"{AA}.aramaic",
    "syryjski": f"{AA}.syriac",
    "maltański": f"{AA}.maltese",
    "amharski": f"{AA}.ethiosemitic.amharic",
    "tigrinia": f"{AA}.ethiosemitic.tigrinya",
    "tigre": f"{AA}.ethiosemitic.tigre",
    "afar": f"{AA}.cushitic.lowland.afar",
    "oromo": f"{AA}.cushitic.lowland.oromo",
    "somalijski": f"{AA}.cushitic.lowland.somali",
    "bedża": f"{AA}.cushitic.beja",
    "blin": f"{AA}.cushitic.agaw.bilen",
    "wolaytta": f"{AA}.omotic.ometo.wolaytta",
    "hausa": f"{AA}.chadic.hausa",
    "kabylski": f"{AA}.berber.kabyle",
    "zenaga": f"{AA}.berber.zenaga",
    # ---- Niger-Congo ----
    "suahili": f"{BT}.swahili",
    "lingala": f"{BT}.lingala",
    "kinyarwanda": f"{BT}.kinyarwanda",
    "rundi": f"{BT}.kirundi",
    "luganda": f"{BT}.ganda",
    "kikuju": f"{BT}.gikuyu",
    "shona": f"{BT}.shona",
    "luba-lulua": f"{BT}.luba_kasai",
    "bemba": f"{BT}.bemba.bemba",
    "lamba": f"{BT}.bisa_lamba.lamba",
    "tumbuka": f"{BT}.tumbuka.tumbuka",
    "cziczewa": f"{BT}.nyanja_sena.chewa",
    "lozi": f"{SO}.lozi",
    "basaa": f"{BT}.basaa",
    "duala": f"{BT}.duala",
    "ewondo": f"{BT}.ewondo",
    "fang": f"{BT}.fang",
    "herero": f"{BT}.herero",
    "kikamba": f"{BT}.kamba",
    "kimbundu": f"{BT}.kimbundu",
    "kongo": f"{BT}.kongo",
    "kwanyama": f"{BT}.kwanyama",
    "ndonga": f"{BT}.ndonga",
    "luba-katanga": f"{BT}.luba_katanga",
    "mongo": f"{BT}.mongo",
    "nyamwezi": f"{BT}.nyamwezi",
    "sukuma": f"{BT}.sukuma",
    "nyankole": f"{BT}.nyankole",
    "nyoro": f"{BT}.nyoro",
    "umbundu": f"{BT}.umbundu",
    "yao": f"{BT}.yao",
    "zulu": f"{NS}.zulu",
    "xhosa": f"{NS}.xhosa",
    "suazi": f"{NS}.siswati",
    "ndebele południowy": f"{NS}.ndebele_za",
    "ndebele północny": f"{NS}.ndebele_zw",
    "tswana": f"{SO}.setswana",
    "południowy sotho": f"{SO}.sesotho",
    "północny sotho": f"{SO}.sepedi",
    "tsonga": f"{BT}.tswa_ronga.tsonga",
    "joruba": f"{NC}.voltaniger.yoruba",
    "igbo": f"{NC}.voltaniger.igbo",
    "bini": f"{NC}.voltaniger.edoid",
    "twi": f"{NC}.kwa.akan",
    "fanti": f"{NC}.kwa.akan",
    "ga": f"{NC}.kwa.ga",
    "adangme": f"{NC}.kwa.adangme",
    "ewe": f"{NC}.kwa.gbe",
    "fon": f"{NC}.kwa.gbe",
    "nzema": f"{NC}.kwa.nzema",
    "wolof": f"{NC}.atlantic.wolof",
    "ful": f"{NC}.atlantic.fulah",
    "timne": f"{NC}.atlantic.temne",
    "bambara": f"{NC}.mande.bambara",
    "mandingo": f"{NC}.mande.manding",
    "diula": f"{NC}.mande.dyula",
    "kpelle": f"{NC}.mande.kpelle",
    "susu": f"{NC}.mande.susu",
    "mossi": f"{NC}.gur.moore",
    "sango": f"{NC}.sango",
    "ekajuk": f"{NC}.ekajuk",
    "ibibio-efik": f"{NC}.ibibio_efik",
    "tiw": f"{NC}.tiv",
    # ---- Nilo-Saharan ----
    "dinka": "nilosaharan.nilotic.dinka",
    "aczoli": "nilosaharan.nilotic.acholi",
    "luo": "nilosaharan.nilotic.luo",
    "masajski": "nilosaharan.nilotic.maasai",
    "kanuri": "nilosaharan.kanuri",
    # ---- Sino-Tibetan, Kra-Dai, Hmong-Mien, Austroasiatic ----
    "chiński": f"{ST}.sinitic",
    "tybetański": f"{ST}.tibetic.tibetan",
    "dzongka": f"{ST}.tibetic.dzongkha",
    "birmański": f"{ST}.burmish.burmese",
    "newarski": f"{ST}.newaric.newar",
    "lushai": f"{ST}.kukichin.mizo",
    "kaczin": f"{ST}.jingpho",
    "yi (yipho)": f"{ST}.yi",
    "tajski": "kradai.thai",
    "laotański": "kradai.lao",
    "szan": "kradai.shan",
    "zhuang": "kradai.zhuang",
    "hmong-mien": "hmongmien",
    "wietnamski": "austroasiatic.vietnamese",
    "khmerski": "austroasiatic.khmer",
    "khasi": "austroasiatic.khasian.khasi",
    # ---- Dravidian ----
    "tamilski": "dravidian.southern.tamil",
    "malajalam": "dravidian.southern.malayalam",
    "kannada": "dravidian.southern.kannada",
    "telugu": "dravidian.southcentral.telugu",
    "gondi": "dravidian.southcentral.gondi",
    "kurukh": "dravidian.northern.kurukh",
    # ---- Japonic, Koreanic, isolates ----
    "japoński": "japonic.japanese",
    "koreański": "koreanic.korean",
    "baskijski": "isolate.basque",
    "ajnoski": "isolate.ainu",
    "sandawe": "isolate.sandawe",
    "haida": "isolate.haida",
    "kutenai": "isolate.ktunaxa",
    "zuni": "isolate.zuni",
    "washoe": "isolate.washo",
    # ---- Austronesian ----
    "indonezyjski": f"{AN}.malayic.indonesian",
    "malajski": f"{AN}.malayic.malay",
    "iban": f"{AN}.malayic.iban",
    "minangkabau": f"{AN}.malayic.minangkabau",
    "aceh": f"{AN}.acehnese",
    "balijski": f"{AN}.balinese",
    "buginese": f"{AN}.buginese",
    "gayo": f"{AN}.gayo",
    "gorontalo": f"{AN}.gorontalo",
    "jawajski": f"{AN}.javanese",
    "madurski": f"{AN}.madurese",
    "mandar": f"{AN}.mandar",
    "nias": f"{AN}.nias",
    "sasak": f"{AN}.sasak",
    "sundajski": f"{AN}.sundanese",
    "palau": f"{AN}.palauan",
    "chamorro": f"{AN}.chamorro",
    "tetum": f"{AN}.tetun",
    "malgaski": f"{AN}.malagasy",
    "filipiński": f"{PH}.filipino",
    "pilipino": f"{PH}.filipino",
    "cebuański": f"{PH}.cebuano",
    "hiligaynon": f"{PH}.hiligaynon",
    "iloko": f"{PH}.ilocano",
    "pampango": f"{PH}.kapampangan",
    "pangasinan": f"{PH}.pangasinan",
    "waray": f"{PH}.waray",
    "fidżyjski": f"{OC}.fijian",
    "hawajski": f"{OC}.hawaiian",
    "samoański": f"{OC}.samoan",
    "tonga": f"{OC}.tongan",
    "chuukese": f"{OC}.chuukese",
    "maoryski": f"{OC}.maori",
    "maoryski Wysp Cooka": f"{OC}.cook_islands_maori",
    "niue": f"{OC}.niuean",
    "rapanui": f"{OC}.rapanui",
    "tahitański": f"{OC}.tahitian",
    "tokelau": f"{OC}.tokelauan",
    "kiribati": f"{OC}.gilbertese",
    "kosraean": f"{OC}.kosraean",
    "pohnpei": f"{OC}.pohnpeian",
    "yap": f"{OC}.yapese",
    # ---- Creoles and pidgins ----
    "haitański": f"{CR}.french_based.haitian",
    "papiamento": f"{CR}.portuguese_based.papiamento",
    "Tok pisin": f"{CR}.english_based.tok_pisin",
    "bislama": f"{CR}.english_based.bislama",
    "sranan tongo": f"{CR}.english_based.sranan",
    "hiri motu": f"{CR}.hiri_motu",
    # ---- the Americas ----
    "inuktitut": "eskimoaleut.inuktitut",
    "inupiak": "eskimoaleut.inupiaq",
    "grenlandzki": "eskimoaleut.greenlandic",
    "aleucki": "eskimoaleut.aleut",
    "odżibwe": "algic.ojibwe",
    "mi'kmaq": "algic.eastern.mikmaq",
    "siksika": "algic.blackfoot",
    "arapaho": "algic.arapaho",
    "czejeński": "algic.cheyenne",
    "chipewyan": f"{ND}.dene",
    "dogrib": f"{ND}.tlicho",
    "gwich'iński": f"{ND}.gwichin",
    "slavey": f"{ND}.slavey",
    "hupa": "nadene.hupa",
    "navaho": "nadene.navajo",
    "mohawk": "iroquoian.mohawk",
    "czirokeski": "iroquoian.cherokee",
    "czoktaw": "muskogean.choctaw",
    "krik": "muskogean.creek",
    "kaddo": "caddoan.caddo",
    "dakota": "siouan.dakota",
    "tsimszian": "tsimshianic.tsimshian",
    "nahuatl": "utoaztecan.nahuatl",
    "zapotec": "otomanguean.zapotecan.zapoteco",
    "keczua": "quechuan.quechua",
    "ajmara": "aymaran.aymara",
    "guarani": "tupian.tupiguarani.guarani",
    "mapuche": "araucanian.mapuche",
    # ---- signed, constructed, unclassified ----
    "polski język migowy": "signlanguage.pjm",
    "esperanto": "other.esperanto",
    "inne - niesklasyfikowane": "other",
}
NOT_STATED = {"Nieustalony"}


def resolve(label):
    if label in NOT_STATED:
        return None
    if label not in NAMES:
        raise KeyError(f"pl2021: unmapped label {label!r}")
    return NAMES[label]
